// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// RUN: %clang_cc1 -triple riscv64 -target-feature +xtheadvector \
// RUN:   -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:   opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-IR %s

// Modified from the original test from:
// https://github.com/ruyisdk/llvm-project/issues/141

#include <riscv_vector.h>

// CHECK-IR-LABEL: define dso_local <vscale x 2 x float> @test1
// CHECK-IR-SAME: (<vscale x 2 x float> [[X:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 2 x float> [[X]] to <vscale x 2 x i32>
// CHECK-IR-NEXT:    [[TMP1:%.*]] = call <vscale x 2 x i32> @llvm.riscv.th.vor.mask.nxv2i32.i32.i64(<vscale x 2 x i32> [[TMP0]], <vscale x 2 x i32> [[TMP0]], i32 -1, <vscale x 2 x i1> [[MASK]], i64 [[VL]])
// CHECK-IR-NEXT:    [[TMP2:%.*]] = bitcast <vscale x 2 x i32> [[TMP1]] to <vscale x 2 x float>
// CHECK-IR-NEXT:    ret <vscale x 2 x float> [[TMP2]]
//
vfloat32m1_t test1(vfloat32m1_t x, vbool32_t mask, size_t vl)
{
    vuint32m1_t xtmp = __riscv_vreinterpret_v_f32m1_u32m1(x);
    xtmp = __riscv_vor_vx_u32m1_mu(mask, xtmp, xtmp, 0xffffffff, vl);
    return __riscv_vreinterpret_v_u32m1_f32m1(xtmp);
}

// CHECK-IR-LABEL: define dso_local <vscale x 2 x float> @test2
// CHECK-IR-SAME: (<vscale x 2 x float> [[X:%.*]], <vscale x 2 x i1> [[MASK:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 2 x float> [[X]] to <vscale x 2 x i32>
// CHECK-IR-NEXT:    [[TMP1:%.*]] = call <vscale x 2 x i32> @llvm.riscv.th.vor.mask.nxv2i32.i32.i64(<vscale x 2 x i32> [[TMP0]], <vscale x 2 x i32> [[TMP0]], i32 -1, <vscale x 2 x i1> [[MASK]], i64 [[VL]])
// CHECK-IR-NEXT:    [[TMP2:%.*]] = bitcast <vscale x 2 x i32> [[TMP1]] to <vscale x 2 x float>
// CHECK-IR-NEXT:    ret <vscale x 2 x float> [[TMP2]]
//
vfloat32m1_t test2(vfloat32m1_t x, vbool32_t mask, size_t vl)
{
    vuint32m1_t xtmp = __riscv_vreinterpret_v_f32m1_u32m1(x);
    xtmp = __riscv_vor_vx_u32m1_m(mask, xtmp, xtmp, 0xffffffff, vl);
    return __riscv_vreinterpret_v_u32m1_f32m1(xtmp);
}
