// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// RUN: %clang_cc1 -triple riscv64 -target-feature +xtheadvector \
// RUN:   -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:   opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-IR %s

#include <riscv_vector.h>

// Modified from the original test from:
// https://github.com/ruyisdk/llvm-project/issues/131

// CHECK-IR-LABEL: define dso_local void @transpose8x8_ps
// CHECK-IR-SAME: (ptr noundef [[_R0L:%.*]], ptr noundef [[_R0H:%.*]], ptr noundef [[_R1L:%.*]], ptr noundef [[_R1H:%.*]], ptr noundef [[_R2L:%.*]], ptr noundef [[_R2H:%.*]], ptr noundef [[_R3L:%.*]], ptr noundef [[_R3H:%.*]], ptr noundef [[_R4L:%.*]], ptr noundef [[_R4H:%.*]], ptr noundef [[_R5L:%.*]], ptr noundef [[_R5H:%.*]], ptr noundef [[_R6L:%.*]], ptr noundef [[_R6H:%.*]], ptr noundef [[_R7L:%.*]], ptr noundef [[_R7H:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP:%.*]] = alloca [64 x float], align 4
// CHECK-IR-NEXT:    [[TMP0:%.*]] = load <vscale x 2 x float>, ptr [[_R0L]], align 4
// CHECK-IR-NEXT:    [[TMP1:%.*]] = load <vscale x 2 x float>, ptr [[_R1L]], align 4
// CHECK-IR-NEXT:    [[TMP2:%.*]] = load <vscale x 2 x float>, ptr [[_R2L]], align 4
// CHECK-IR-NEXT:    [[TMP3:%.*]] = load <vscale x 2 x float>, ptr [[_R3L]], align 4
// CHECK-IR-NEXT:    [[TMP4:%.*]] = load <vscale x 2 x float>, ptr [[_R4L]], align 4
// CHECK-IR-NEXT:    [[TMP5:%.*]] = load <vscale x 2 x float>, ptr [[_R5L]], align 4
// CHECK-IR-NEXT:    [[TMP6:%.*]] = load <vscale x 2 x float>, ptr [[_R6L]], align 4
// CHECK-IR-NEXT:    [[TMP7:%.*]] = load <vscale x 2 x float>, ptr [[_R7L]], align 4
// CHECK-IR-NEXT:    [[TMP8:%.*]] = insertvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } poison, <vscale x 2 x float> [[TMP0]], 0
// CHECK-IR-NEXT:    [[TMP9:%.*]] = insertvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP8]], <vscale x 2 x float> [[TMP1]], 1
// CHECK-IR-NEXT:    [[TMP10:%.*]] = insertvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP9]], <vscale x 2 x float> [[TMP2]], 2
// CHECK-IR-NEXT:    [[TMP11:%.*]] = insertvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP10]], <vscale x 2 x float> [[TMP3]], 3
// CHECK-IR-NEXT:    [[TMP12:%.*]] = insertvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP11]], <vscale x 2 x float> [[TMP4]], 4
// CHECK-IR-NEXT:    [[TMP13:%.*]] = insertvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP12]], <vscale x 2 x float> [[TMP5]], 5
// CHECK-IR-NEXT:    [[TMP14:%.*]] = insertvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP13]], <vscale x 2 x float> [[TMP6]], 6
// CHECK-IR-NEXT:    [[TMP15:%.*]] = insertvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP14]], <vscale x 2 x float> [[TMP7]], 7
// CHECK-IR-NEXT:    [[TMP16:%.*]] = load <vscale x 2 x float>, ptr [[_R0H]], align 4
// CHECK-IR-NEXT:    [[TMP17:%.*]] = load <vscale x 2 x float>, ptr [[_R1H]], align 4
// CHECK-IR-NEXT:    [[TMP18:%.*]] = load <vscale x 2 x float>, ptr [[_R2H]], align 4
// CHECK-IR-NEXT:    [[TMP19:%.*]] = load <vscale x 2 x float>, ptr [[_R3H]], align 4
// CHECK-IR-NEXT:    [[TMP20:%.*]] = load <vscale x 2 x float>, ptr [[_R4H]], align 4
// CHECK-IR-NEXT:    [[TMP21:%.*]] = load <vscale x 2 x float>, ptr [[_R5H]], align 4
// CHECK-IR-NEXT:    [[TMP22:%.*]] = load <vscale x 2 x float>, ptr [[_R6H]], align 4
// CHECK-IR-NEXT:    [[TMP23:%.*]] = load <vscale x 2 x float>, ptr [[_R7H]], align 4
// CHECK-IR-NEXT:    [[TMP24:%.*]] = insertvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } poison, <vscale x 2 x float> [[TMP16]], 0
// CHECK-IR-NEXT:    [[TMP25:%.*]] = insertvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP24]], <vscale x 2 x float> [[TMP17]], 1
// CHECK-IR-NEXT:    [[TMP26:%.*]] = insertvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP25]], <vscale x 2 x float> [[TMP18]], 2
// CHECK-IR-NEXT:    [[TMP27:%.*]] = insertvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP26]], <vscale x 2 x float> [[TMP19]], 3
// CHECK-IR-NEXT:    [[TMP28:%.*]] = insertvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP27]], <vscale x 2 x float> [[TMP20]], 4
// CHECK-IR-NEXT:    [[TMP29:%.*]] = insertvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP28]], <vscale x 2 x float> [[TMP21]], 5
// CHECK-IR-NEXT:    [[TMP30:%.*]] = insertvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP29]], <vscale x 2 x float> [[TMP22]], 6
// CHECK-IR-NEXT:    [[TMP31:%.*]] = insertvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP30]], <vscale x 2 x float> [[TMP23]], 7
// CHECK-IR-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [64 x float], ptr [[TMP]], i64 0, i64 0
// CHECK-IR-NEXT:    [[TMP32:%.*]] = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP15]], 0
// CHECK-IR-NEXT:    [[TMP33:%.*]] = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP15]], 1
// CHECK-IR-NEXT:    [[TMP34:%.*]] = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP15]], 2
// CHECK-IR-NEXT:    [[TMP35:%.*]] = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP15]], 3
// CHECK-IR-NEXT:    [[TMP36:%.*]] = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP15]], 4
// CHECK-IR-NEXT:    [[TMP37:%.*]] = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP15]], 5
// CHECK-IR-NEXT:    [[TMP38:%.*]] = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP15]], 6
// CHECK-IR-NEXT:    [[TMP39:%.*]] = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP15]], 7
// CHECK-IR-NEXT:    call void @llvm.riscv.th.vsseg8e.nxv2f32.i64(<vscale x 2 x float> [[TMP32]], <vscale x 2 x float> [[TMP33]], <vscale x 2 x float> [[TMP34]], <vscale x 2 x float> [[TMP35]], <vscale x 2 x float> [[TMP36]], <vscale x 2 x float> [[TMP37]], <vscale x 2 x float> [[TMP38]], <vscale x 2 x float> [[TMP39]], ptr [[ARRAYIDX]], i64 [[VL]])
// CHECK-IR-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds [64 x float], ptr [[TMP]], i64 0, i64 32
// CHECK-IR-NEXT:    [[TMP40:%.*]] = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP31]], 0
// CHECK-IR-NEXT:    [[TMP41:%.*]] = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP31]], 1
// CHECK-IR-NEXT:    [[TMP42:%.*]] = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP31]], 2
// CHECK-IR-NEXT:    [[TMP43:%.*]] = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP31]], 3
// CHECK-IR-NEXT:    [[TMP44:%.*]] = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP31]], 4
// CHECK-IR-NEXT:    [[TMP45:%.*]] = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP31]], 5
// CHECK-IR-NEXT:    [[TMP46:%.*]] = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP31]], 6
// CHECK-IR-NEXT:    [[TMP47:%.*]] = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float> } [[TMP31]], 7
// CHECK-IR-NEXT:    call void @llvm.riscv.th.vsseg8e.nxv2f32.i64(<vscale x 2 x float> [[TMP40]], <vscale x 2 x float> [[TMP41]], <vscale x 2 x float> [[TMP42]], <vscale x 2 x float> [[TMP43]], <vscale x 2 x float> [[TMP44]], <vscale x 2 x float> [[TMP45]], <vscale x 2 x float> [[TMP46]], <vscale x 2 x float> [[TMP47]], ptr [[ARRAYIDX1]], i64 [[VL]])
// CHECK-IR-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [64 x float], ptr [[TMP]], i64 0, i64 0
// CHECK-IR-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds float, ptr [[ARRAYDECAY]], i64 0
// CHECK-IR-NEXT:    [[TMP48:%.*]] = call <vscale x 2 x float> @llvm.riscv.th.vle.nxv2f32.i64(<vscale x 2 x float> poison, ptr [[ADD_PTR]], i64 [[VL]])
// CHECK-IR-NEXT:    store <vscale x 2 x float> [[TMP48]], ptr [[_R0L]], align 4
// CHECK-IR-NEXT:    [[ADD_PTR2:%.*]] = getelementptr inbounds float, ptr [[ARRAYDECAY]], i64 4
// CHECK-IR-NEXT:    [[TMP49:%.*]] = call <vscale x 2 x float> @llvm.riscv.th.vle.nxv2f32.i64(<vscale x 2 x float> poison, ptr [[ADD_PTR2]], i64 [[VL]])
// CHECK-IR-NEXT:    store <vscale x 2 x float> [[TMP49]], ptr [[_R0H]], align 4
// CHECK-IR-NEXT:    [[ADD_PTR3:%.*]] = getelementptr inbounds float, ptr [[ARRAYDECAY]], i64 8
// CHECK-IR-NEXT:    [[TMP50:%.*]] = call <vscale x 2 x float> @llvm.riscv.th.vle.nxv2f32.i64(<vscale x 2 x float> poison, ptr [[ADD_PTR3]], i64 [[VL]])
// CHECK-IR-NEXT:    store <vscale x 2 x float> [[TMP50]], ptr [[_R1L]], align 4
// CHECK-IR-NEXT:    [[ADD_PTR4:%.*]] = getelementptr inbounds float, ptr [[ARRAYDECAY]], i64 12
// CHECK-IR-NEXT:    [[TMP51:%.*]] = call <vscale x 2 x float> @llvm.riscv.th.vle.nxv2f32.i64(<vscale x 2 x float> poison, ptr [[ADD_PTR4]], i64 [[VL]])
// CHECK-IR-NEXT:    store <vscale x 2 x float> [[TMP51]], ptr [[_R1H]], align 4
// CHECK-IR-NEXT:    [[ADD_PTR5:%.*]] = getelementptr inbounds float, ptr [[ARRAYDECAY]], i64 16
// CHECK-IR-NEXT:    [[TMP52:%.*]] = call <vscale x 2 x float> @llvm.riscv.th.vle.nxv2f32.i64(<vscale x 2 x float> poison, ptr [[ADD_PTR5]], i64 [[VL]])
// CHECK-IR-NEXT:    store <vscale x 2 x float> [[TMP52]], ptr [[_R2L]], align 4
// CHECK-IR-NEXT:    [[ADD_PTR6:%.*]] = getelementptr inbounds float, ptr [[ARRAYDECAY]], i64 20
// CHECK-IR-NEXT:    [[TMP53:%.*]] = call <vscale x 2 x float> @llvm.riscv.th.vle.nxv2f32.i64(<vscale x 2 x float> poison, ptr [[ADD_PTR6]], i64 [[VL]])
// CHECK-IR-NEXT:    store <vscale x 2 x float> [[TMP53]], ptr [[_R2H]], align 4
// CHECK-IR-NEXT:    [[ADD_PTR7:%.*]] = getelementptr inbounds float, ptr [[ARRAYDECAY]], i64 24
// CHECK-IR-NEXT:    [[TMP54:%.*]] = call <vscale x 2 x float> @llvm.riscv.th.vle.nxv2f32.i64(<vscale x 2 x float> poison, ptr [[ADD_PTR7]], i64 [[VL]])
// CHECK-IR-NEXT:    store <vscale x 2 x float> [[TMP54]], ptr [[_R3L]], align 4
// CHECK-IR-NEXT:    [[ADD_PTR8:%.*]] = getelementptr inbounds float, ptr [[ARRAYDECAY]], i64 28
// CHECK-IR-NEXT:    [[TMP55:%.*]] = call <vscale x 2 x float> @llvm.riscv.th.vle.nxv2f32.i64(<vscale x 2 x float> poison, ptr [[ADD_PTR8]], i64 [[VL]])
// CHECK-IR-NEXT:    store <vscale x 2 x float> [[TMP55]], ptr [[_R3H]], align 4
// CHECK-IR-NEXT:    [[ADD_PTR9:%.*]] = getelementptr inbounds float, ptr [[ARRAYDECAY]], i64 32
// CHECK-IR-NEXT:    [[TMP56:%.*]] = call <vscale x 2 x float> @llvm.riscv.th.vle.nxv2f32.i64(<vscale x 2 x float> poison, ptr [[ADD_PTR9]], i64 [[VL]])
// CHECK-IR-NEXT:    store <vscale x 2 x float> [[TMP56]], ptr [[_R4L]], align 4
// CHECK-IR-NEXT:    [[ADD_PTR10:%.*]] = getelementptr inbounds float, ptr [[ARRAYDECAY]], i64 36
// CHECK-IR-NEXT:    [[TMP57:%.*]] = call <vscale x 2 x float> @llvm.riscv.th.vle.nxv2f32.i64(<vscale x 2 x float> poison, ptr [[ADD_PTR10]], i64 [[VL]])
// CHECK-IR-NEXT:    store <vscale x 2 x float> [[TMP57]], ptr [[_R4H]], align 4
// CHECK-IR-NEXT:    [[ADD_PTR11:%.*]] = getelementptr inbounds float, ptr [[ARRAYDECAY]], i64 40
// CHECK-IR-NEXT:    [[TMP58:%.*]] = call <vscale x 2 x float> @llvm.riscv.th.vle.nxv2f32.i64(<vscale x 2 x float> poison, ptr [[ADD_PTR11]], i64 [[VL]])
// CHECK-IR-NEXT:    store <vscale x 2 x float> [[TMP58]], ptr [[_R5L]], align 4
// CHECK-IR-NEXT:    [[ADD_PTR12:%.*]] = getelementptr inbounds float, ptr [[ARRAYDECAY]], i64 44
// CHECK-IR-NEXT:    [[TMP59:%.*]] = call <vscale x 2 x float> @llvm.riscv.th.vle.nxv2f32.i64(<vscale x 2 x float> poison, ptr [[ADD_PTR12]], i64 [[VL]])
// CHECK-IR-NEXT:    store <vscale x 2 x float> [[TMP59]], ptr [[_R5H]], align 4
// CHECK-IR-NEXT:    [[ADD_PTR13:%.*]] = getelementptr inbounds float, ptr [[ARRAYDECAY]], i64 48
// CHECK-IR-NEXT:    [[TMP60:%.*]] = call <vscale x 2 x float> @llvm.riscv.th.vle.nxv2f32.i64(<vscale x 2 x float> poison, ptr [[ADD_PTR13]], i64 [[VL]])
// CHECK-IR-NEXT:    store <vscale x 2 x float> [[TMP60]], ptr [[_R6L]], align 4
// CHECK-IR-NEXT:    [[ADD_PTR14:%.*]] = getelementptr inbounds float, ptr [[ARRAYDECAY]], i64 52
// CHECK-IR-NEXT:    [[TMP61:%.*]] = call <vscale x 2 x float> @llvm.riscv.th.vle.nxv2f32.i64(<vscale x 2 x float> poison, ptr [[ADD_PTR14]], i64 [[VL]])
// CHECK-IR-NEXT:    store <vscale x 2 x float> [[TMP61]], ptr [[_R6H]], align 4
// CHECK-IR-NEXT:    [[ADD_PTR15:%.*]] = getelementptr inbounds float, ptr [[ARRAYDECAY]], i64 56
// CHECK-IR-NEXT:    [[TMP62:%.*]] = call <vscale x 2 x float> @llvm.riscv.th.vle.nxv2f32.i64(<vscale x 2 x float> poison, ptr [[ADD_PTR15]], i64 [[VL]])
// CHECK-IR-NEXT:    store <vscale x 2 x float> [[TMP62]], ptr [[_R7L]], align 4
// CHECK-IR-NEXT:    [[ADD_PTR16:%.*]] = getelementptr inbounds float, ptr [[ARRAYDECAY]], i64 60
// CHECK-IR-NEXT:    [[TMP63:%.*]] = call <vscale x 2 x float> @llvm.riscv.th.vle.nxv2f32.i64(<vscale x 2 x float> poison, ptr [[ADD_PTR16]], i64 [[VL]])
// CHECK-IR-NEXT:    store <vscale x 2 x float> [[TMP63]], ptr [[_R7H]], align 4
// CHECK-IR-NEXT:    ret void
//
void transpose8x8_ps(vfloat32m1_t* _r0l, vfloat32m1_t* _r0h,
                     vfloat32m1_t* _r1l, vfloat32m1_t* _r1h,
                     vfloat32m1_t* _r2l, vfloat32m1_t* _r2h,
                     vfloat32m1_t* _r3l, vfloat32m1_t* _r3h,
                     vfloat32m1_t* _r4l, vfloat32m1_t* _r4h,
                     vfloat32m1_t* _r5l, vfloat32m1_t* _r5h,
                     vfloat32m1_t* _r6l, vfloat32m1_t* _r6h,
                     vfloat32m1_t* _r7l, vfloat32m1_t* _r7h, size_t vl)
{
    float tmp[64];
    vfloat32m1x8_t _rl = __riscv_vcreate_v_f32m1x8(*_r0l, *_r1l, *_r2l, *_r3l, *_r4l, *_r5l, *_r6l, *_r7l);
    vfloat32m1x8_t _rh = __riscv_vcreate_v_f32m1x8(*_r0h, *_r1h, *_r2h, *_r3h, *_r4h, *_r5h, *_r6h, *_r7h);
    __riscv_vsseg8e32_v_f32m1x8(&tmp[0], _rl, vl);
    __riscv_vsseg8e32_v_f32m1x8(&tmp[32], _rh, vl);
    float* ptr = (float*)tmp;
    *_r0l = __riscv_vle32_v_f32m1(ptr + 0 * 4, vl);
    *_r0h = __riscv_vle32_v_f32m1(ptr + 1 * 4, vl);
    *_r1l = __riscv_vle32_v_f32m1(ptr + 2 * 4, vl);
    *_r1h = __riscv_vle32_v_f32m1(ptr + 3 * 4, vl);
    *_r2l = __riscv_vle32_v_f32m1(ptr + 4 * 4, vl);
    *_r2h = __riscv_vle32_v_f32m1(ptr + 5 * 4, vl);
    *_r3l = __riscv_vle32_v_f32m1(ptr + 6 * 4, vl);
    *_r3h = __riscv_vle32_v_f32m1(ptr + 7 * 4, vl);
    *_r4l = __riscv_vle32_v_f32m1(ptr + 8 * 4, vl);
    *_r4h = __riscv_vle32_v_f32m1(ptr + 9 * 4, vl);
    *_r5l = __riscv_vle32_v_f32m1(ptr + 10 * 4, vl);
    *_r5h = __riscv_vle32_v_f32m1(ptr + 11 * 4, vl);
    *_r6l = __riscv_vle32_v_f32m1(ptr + 12 * 4, vl);
    *_r6h = __riscv_vle32_v_f32m1(ptr + 13 * 4, vl);
    *_r7l = __riscv_vle32_v_f32m1(ptr + 14 * 4, vl);
    *_r7h = __riscv_vle32_v_f32m1(ptr + 15 * 4, vl);
}
