// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// RUN: %clang_cc1 -triple riscv64 -target-feature +xtheadvector \
// RUN:   -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:   opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-IR %s

#include <riscv_vector.h>

// CHECK-IR-LABEL: define dso_local void @index_vec
// CHECK-IR-SAME: (ptr noundef [[A:%.*]], ptr noundef [[B:%.*]], ptr noundef [[C:%.*]], i32 noundef signext [[N:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.th.vsetvlmax.i64(i64 2, i64 0)
// CHECK-IR-NEXT:    [[TMP1:%.*]] = call <vscale x 2 x i32> @llvm.riscv.th.vid.nxv2i32.i64(<vscale x 2 x i32> poison, i64 [[TMP0]])
// CHECK-IR-NEXT:    br label [[FOR_COND:%.*]]
// CHECK-IR:       for.cond:
// CHECK-IR-NEXT:    [[VEC_I_0:%.*]] = phi <vscale x 2 x i32> [ [[TMP1]], [[ENTRY:%.*]] ], [ [[TMP7:%.*]], [[FOR_INC:%.*]] ]
// CHECK-IR-NEXT:    [[N_ADDR_0:%.*]] = phi i32 [ [[N]], [[ENTRY]] ], [ [[CONV3:%.*]], [[FOR_INC]] ]
// CHECK-IR-NEXT:    [[C_ADDR_0:%.*]] = phi ptr [ [[C]], [[ENTRY]] ], [ [[ADD_PTR5:%.*]], [[FOR_INC]] ]
// CHECK-IR-NEXT:    [[B_ADDR_0:%.*]] = phi ptr [ [[B]], [[ENTRY]] ], [ [[ADD_PTR4:%.*]], [[FOR_INC]] ]
// CHECK-IR-NEXT:    [[A_ADDR_0:%.*]] = phi ptr [ [[A]], [[ENTRY]] ], [ [[ADD_PTR:%.*]], [[FOR_INC]] ]
// CHECK-IR-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[N_ADDR_0]], 0
// CHECK-IR-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK-IR:       for.body:
// CHECK-IR-NEXT:    [[CONV:%.*]] = sext i32 [[N_ADDR_0]] to i64
// CHECK-IR-NEXT:    [[TMP2:%.*]] = call i64 @llvm.riscv.th.vsetvl.i64(i64 [[CONV]], i64 3, i64 1)
// CHECK-IR-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x double> @llvm.riscv.th.vfwcvt.f.xu.v.nxv2f64.nxv2i32.i64(<vscale x 2 x double> poison, <vscale x 2 x i32> [[VEC_I_0]], i64 [[TMP2]])
// CHECK-IR-NEXT:    [[TMP4:%.*]] = call <vscale x 2 x double> @llvm.riscv.th.vle.nxv2f64.i64(<vscale x 2 x double> poison, ptr [[B_ADDR_0]], i64 [[TMP2]])
// CHECK-IR-NEXT:    [[TMP5:%.*]] = call <vscale x 2 x double> @llvm.riscv.th.vle.nxv2f64.i64(<vscale x 2 x double> poison, ptr [[C_ADDR_0]], i64 [[TMP2]])
// CHECK-IR-NEXT:    [[TMP6:%.*]] = call <vscale x 2 x double> @llvm.riscv.th.vfmadd.nxv2f64.nxv2f64.i64(<vscale x 2 x double> [[TMP5]], <vscale x 2 x double> [[TMP3]], <vscale x 2 x double> [[TMP4]], i64 7, i64 [[TMP2]])
// CHECK-IR-NEXT:    call void @llvm.riscv.th.vse.nxv2f64.i64(<vscale x 2 x double> [[TMP6]], ptr [[A_ADDR_0]], i64 [[TMP2]])
// CHECK-IR-NEXT:    [[CONV1:%.*]] = trunc i64 [[TMP2]] to i32
// CHECK-IR-NEXT:    [[TMP7]] = call <vscale x 2 x i32> @llvm.riscv.th.vadd.nxv2i32.i32.i64(<vscale x 2 x i32> poison, <vscale x 2 x i32> [[VEC_I_0]], i32 [[CONV1]], i64 [[TMP2]])
// CHECK-IR-NEXT:    br label [[FOR_INC]]
// CHECK-IR:       for.inc:
// CHECK-IR-NEXT:    [[CONV2:%.*]] = sext i32 [[N_ADDR_0]] to i64
// CHECK-IR-NEXT:    [[SUB:%.*]] = sub i64 [[CONV2]], [[TMP2]]
// CHECK-IR-NEXT:    [[CONV3]] = trunc i64 [[SUB]] to i32
// CHECK-IR-NEXT:    [[ADD_PTR]] = getelementptr inbounds double, ptr [[A_ADDR_0]], i64 [[TMP2]]
// CHECK-IR-NEXT:    [[ADD_PTR4]] = getelementptr inbounds double, ptr [[B_ADDR_0]], i64 [[TMP2]]
// CHECK-IR-NEXT:    [[ADD_PTR5]] = getelementptr inbounds double, ptr [[C_ADDR_0]], i64 [[TMP2]]
// CHECK-IR-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP4:![0-9]+]]
// CHECK-IR:       for.end:
// CHECK-IR-NEXT:    ret void
//
void index_vec(double *a, double *b, double *c, int n) {
  size_t vlmax = __riscv_vsetvlmax_e32m1();
  vuint32m1_t vec_i = __riscv_vid_v_u32m1(vlmax);
  for (size_t vl; n > 0; n -= vl, a += vl, b += vl, c += vl) {
    vl = __riscv_vsetvl_e64m2(n);

    vfloat64m2_t vec_i_double = __riscv_vfwcvt_f_xu_v_f64m2(vec_i, vl);

    vfloat64m2_t vec_b = __riscv_vle64_v_f64m2(b, vl);
    vfloat64m2_t vec_c = __riscv_vle64_v_f64m2(c, vl);

    vfloat64m2_t vec_a = __riscv_vfmadd_vv_f64m2(vec_c, vec_i_double, vec_b, vl);
    __riscv_vse64_v_f64m2(a, vec_a, vl);

    vec_i = __riscv_vadd_vx_u32m1(vec_i, vl, vl);
  }
}
