// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// RUN: %clang_cc1 -triple riscv64 -target-feature +xtheadvector \
// RUN:   -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:   opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-IR %s

#include <riscv_vector.h>

// CHECK-IR-LABEL: define dso_local ptr @memcpy_vec
// CHECK-IR-SAME: (ptr noalias noundef [[DESTINATION:%.*]], ptr noalias noundef [[SOURCE:%.*]], i64 noundef [[N:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    br label [[FOR_COND:%.*]]
// CHECK-IR:       for.cond:
// CHECK-IR-NEXT:    [[N_ADDR_0:%.*]] = phi i64 [ [[N]], [[ENTRY:%.*]] ], [ [[SUB:%.*]], [[FOR_INC:%.*]] ]
// CHECK-IR-NEXT:    [[DST_0:%.*]] = phi ptr [ [[DESTINATION]], [[ENTRY]] ], [ [[ADD_PTR1:%.*]], [[FOR_INC]] ]
// CHECK-IR-NEXT:    [[SRC_0:%.*]] = phi ptr [ [[SOURCE]], [[ENTRY]] ], [ [[ADD_PTR:%.*]], [[FOR_INC]] ]
// CHECK-IR-NEXT:    [[CMP:%.*]] = icmp ugt i64 [[N_ADDR_0]], 0
// CHECK-IR-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_END:%.*]]
// CHECK-IR:       for.body:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = call i64 @llvm.riscv.th.vsetvl.i64(i64 [[N_ADDR_0]], i64 0, i64 3)
// CHECK-IR-NEXT:    [[TMP1:%.*]] = call <vscale x 64 x i8> @llvm.riscv.th.vle.nxv64i8.i64(<vscale x 64 x i8> poison, ptr [[SRC_0]], i64 [[TMP0]])
// CHECK-IR-NEXT:    call void @llvm.riscv.th.vse.nxv64i8.i64(<vscale x 64 x i8> [[TMP1]], ptr [[DST_0]], i64 [[TMP0]])
// CHECK-IR-NEXT:    br label [[FOR_INC]]
// CHECK-IR:       for.inc:
// CHECK-IR-NEXT:    [[SUB]] = sub i64 [[N_ADDR_0]], [[TMP0]]
// CHECK-IR-NEXT:    [[ADD_PTR]] = getelementptr inbounds i8, ptr [[SRC_0]], i64 [[TMP0]]
// CHECK-IR-NEXT:    [[ADD_PTR1]] = getelementptr inbounds i8, ptr [[DST_0]], i64 [[TMP0]]
// CHECK-IR-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP4:![0-9]+]]
// CHECK-IR:       for.end:
// CHECK-IR-NEXT:    ret ptr [[DESTINATION]]
//
void *memcpy_vec(void *restrict destination, const void *restrict source,
                 size_t n) {
  unsigned char *dst = destination;
  const unsigned char *src = source;
  for (size_t vl; n > 0; n -= vl, src += vl, dst += vl) {
    vl = __riscv_vsetvl_e8m8(n);
    vuint8m8_t vec_src = __riscv_vle8_v_u8m8(src, vl);
    __riscv_vse8_v_u8m8(dst, vec_src, vl);
  }
  return destination;
}
