// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// RUN: %clang_cc1 -triple riscv64 -target-feature +xtheadvector \
// RUN:   -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:   opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-IR %s

#include <riscv_vector.h>

// CHECK-IR-LABEL: define dso_local <vscale x 4 x i16> @test_vreinterpret_v_i8m1_i16m1
// CHECK-IR-SAME: (<vscale x 8 x i8> [[SRC:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i8> [[SRC]] to <vscale x 4 x i16>
// CHECK-IR-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vreinterpret_v_i8m1_i16m1(vint8m1_t src) {
  return __riscv_vreinterpret_v_i8m1_i16m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i16> @test_vreinterpret_v_i8m2_i16m2
// CHECK-IR-SAME: (<vscale x 16 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 16 x i8> [[SRC]] to <vscale x 8 x i16>
// CHECK-IR-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vreinterpret_v_i8m2_i16m2(vint8m2_t src) {
  return __riscv_vreinterpret_v_i8m2_i16m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 16 x i16> @test_vreinterpret_v_i8m4_i16m4
// CHECK-IR-SAME: (<vscale x 32 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 32 x i8> [[SRC]] to <vscale x 16 x i16>
// CHECK-IR-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vreinterpret_v_i8m4_i16m4(vint8m4_t src) {
  return __riscv_vreinterpret_v_i8m4_i16m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 32 x i16> @test_vreinterpret_v_i8m8_i16m8
// CHECK-IR-SAME: (<vscale x 64 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 64 x i8> [[SRC]] to <vscale x 32 x i16>
// CHECK-IR-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vint16m8_t test_vreinterpret_v_i8m8_i16m8(vint8m8_t src) {
  return __riscv_vreinterpret_v_i8m8_i16m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 4 x i16> @test_vreinterpret_v_u8m1_u16m1
// CHECK-IR-SAME: (<vscale x 8 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i8> [[SRC]] to <vscale x 4 x i16>
// CHECK-IR-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vreinterpret_v_u8m1_u16m1(vuint8m1_t src) {
  return __riscv_vreinterpret_v_u8m1_u16m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i16> @test_vreinterpret_v_u8m2_u16m2
// CHECK-IR-SAME: (<vscale x 16 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 16 x i8> [[SRC]] to <vscale x 8 x i16>
// CHECK-IR-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vreinterpret_v_u8m2_u16m2(vuint8m2_t src) {
  return __riscv_vreinterpret_v_u8m2_u16m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 16 x i16> @test_vreinterpret_v_u8m4_u16m4
// CHECK-IR-SAME: (<vscale x 32 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 32 x i8> [[SRC]] to <vscale x 16 x i16>
// CHECK-IR-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vreinterpret_v_u8m4_u16m4(vuint8m4_t src) {
  return __riscv_vreinterpret_v_u8m4_u16m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 32 x i16> @test_vreinterpret_v_u8m8_u16m8
// CHECK-IR-SAME: (<vscale x 64 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 64 x i8> [[SRC]] to <vscale x 32 x i16>
// CHECK-IR-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_vreinterpret_v_u8m8_u16m8(vuint8m8_t src) {
  return __riscv_vreinterpret_v_u8m8_u16m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 2 x i32> @test_vreinterpret_v_i8m1_i32m1
// CHECK-IR-SAME: (<vscale x 8 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i8> [[SRC]] to <vscale x 2 x i32>
// CHECK-IR-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vreinterpret_v_i8m1_i32m1(vint8m1_t src) {
  return __riscv_vreinterpret_v_i8m1_i32m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 4 x i32> @test_vreinterpret_v_i8m2_i32m2
// CHECK-IR-SAME: (<vscale x 16 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 16 x i8> [[SRC]] to <vscale x 4 x i32>
// CHECK-IR-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vreinterpret_v_i8m2_i32m2(vint8m2_t src) {
  return __riscv_vreinterpret_v_i8m2_i32m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i32> @test_vreinterpret_v_i8m4_i32m4
// CHECK-IR-SAME: (<vscale x 32 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 32 x i8> [[SRC]] to <vscale x 8 x i32>
// CHECK-IR-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vreinterpret_v_i8m4_i32m4(vint8m4_t src) {
  return __riscv_vreinterpret_v_i8m4_i32m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 16 x i32> @test_vreinterpret_v_i8m8_i32m8
// CHECK-IR-SAME: (<vscale x 64 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 64 x i8> [[SRC]] to <vscale x 16 x i32>
// CHECK-IR-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vreinterpret_v_i8m8_i32m8(vint8m8_t src) {
  return __riscv_vreinterpret_v_i8m8_i32m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 2 x i32> @test_vreinterpret_v_u8m1_u32m1
// CHECK-IR-SAME: (<vscale x 8 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i8> [[SRC]] to <vscale x 2 x i32>
// CHECK-IR-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vreinterpret_v_u8m1_u32m1(vuint8m1_t src) {
  return __riscv_vreinterpret_v_u8m1_u32m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 4 x i32> @test_vreinterpret_v_u8m2_u32m2
// CHECK-IR-SAME: (<vscale x 16 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 16 x i8> [[SRC]] to <vscale x 4 x i32>
// CHECK-IR-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vreinterpret_v_u8m2_u32m2(vuint8m2_t src) {
  return __riscv_vreinterpret_v_u8m2_u32m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i32> @test_vreinterpret_v_u8m4_u32m4
// CHECK-IR-SAME: (<vscale x 32 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 32 x i8> [[SRC]] to <vscale x 8 x i32>
// CHECK-IR-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vreinterpret_v_u8m4_u32m4(vuint8m4_t src) {
  return __riscv_vreinterpret_v_u8m4_u32m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 16 x i32> @test_vreinterpret_v_u8m8_u32m8
// CHECK-IR-SAME: (<vscale x 64 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 64 x i8> [[SRC]] to <vscale x 16 x i32>
// CHECK-IR-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vreinterpret_v_u8m8_u32m8(vuint8m8_t src) {
  return __riscv_vreinterpret_v_u8m8_u32m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 1 x i64> @test_vreinterpret_v_i8m1_i64m1
// CHECK-IR-SAME: (<vscale x 8 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i8> [[SRC]] to <vscale x 1 x i64>
// CHECK-IR-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vreinterpret_v_i8m1_i64m1(vint8m1_t src) {
  return __riscv_vreinterpret_v_i8m1_i64m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 2 x i64> @test_vreinterpret_v_i8m2_i64m2
// CHECK-IR-SAME: (<vscale x 16 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 16 x i8> [[SRC]] to <vscale x 2 x i64>
// CHECK-IR-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vreinterpret_v_i8m2_i64m2(vint8m2_t src) {
  return __riscv_vreinterpret_v_i8m2_i64m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 4 x i64> @test_vreinterpret_v_i8m4_i64m4
// CHECK-IR-SAME: (<vscale x 32 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 32 x i8> [[SRC]] to <vscale x 4 x i64>
// CHECK-IR-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vreinterpret_v_i8m4_i64m4(vint8m4_t src) {
  return __riscv_vreinterpret_v_i8m4_i64m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i64> @test_vreinterpret_v_i8m8_i64m8
// CHECK-IR-SAME: (<vscale x 64 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 64 x i8> [[SRC]] to <vscale x 8 x i64>
// CHECK-IR-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vreinterpret_v_i8m8_i64m8(vint8m8_t src) {
  return __riscv_vreinterpret_v_i8m8_i64m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 1 x i64> @test_vreinterpret_v_u8m1_u64m1
// CHECK-IR-SAME: (<vscale x 8 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i8> [[SRC]] to <vscale x 1 x i64>
// CHECK-IR-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vreinterpret_v_u8m1_u64m1(vuint8m1_t src) {
  return __riscv_vreinterpret_v_u8m1_u64m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 2 x i64> @test_vreinterpret_v_u8m2_u64m2
// CHECK-IR-SAME: (<vscale x 16 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 16 x i8> [[SRC]] to <vscale x 2 x i64>
// CHECK-IR-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vreinterpret_v_u8m2_u64m2(vuint8m2_t src) {
  return __riscv_vreinterpret_v_u8m2_u64m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 4 x i64> @test_vreinterpret_v_u8m4_u64m4
// CHECK-IR-SAME: (<vscale x 32 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 32 x i8> [[SRC]] to <vscale x 4 x i64>
// CHECK-IR-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vreinterpret_v_u8m4_u64m4(vuint8m4_t src) {
  return __riscv_vreinterpret_v_u8m4_u64m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i64> @test_vreinterpret_v_u8m8_u64m8
// CHECK-IR-SAME: (<vscale x 64 x i8> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 64 x i8> [[SRC]] to <vscale x 8 x i64>
// CHECK-IR-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vreinterpret_v_u8m8_u64m8(vuint8m8_t src) {
  return __riscv_vreinterpret_v_u8m8_u64m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i8> @test_vreinterpret_v_i16m1_i8m1
// CHECK-IR-SAME: (<vscale x 4 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 4 x i16> [[SRC]] to <vscale x 8 x i8>
// CHECK-IR-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vreinterpret_v_i16m1_i8m1(vint16m1_t src) {
  return __riscv_vreinterpret_v_i16m1_i8m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 16 x i8> @test_vreinterpret_v_i16m2_i8m2
// CHECK-IR-SAME: (<vscale x 8 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i16> [[SRC]] to <vscale x 16 x i8>
// CHECK-IR-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vint8m2_t test_vreinterpret_v_i16m2_i8m2(vint16m2_t src) {
  return __riscv_vreinterpret_v_i16m2_i8m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 32 x i8> @test_vreinterpret_v_i16m4_i8m4
// CHECK-IR-SAME: (<vscale x 16 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 16 x i16> [[SRC]] to <vscale x 32 x i8>
// CHECK-IR-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vint8m4_t test_vreinterpret_v_i16m4_i8m4(vint16m4_t src) {
  return __riscv_vreinterpret_v_i16m4_i8m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 64 x i8> @test_vreinterpret_v_i16m8_i8m8
// CHECK-IR-SAME: (<vscale x 32 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 32 x i16> [[SRC]] to <vscale x 64 x i8>
// CHECK-IR-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vint8m8_t test_vreinterpret_v_i16m8_i8m8(vint16m8_t src) {
  return __riscv_vreinterpret_v_i16m8_i8m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i8> @test_vreinterpret_v_u16m1_u8m1
// CHECK-IR-SAME: (<vscale x 4 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 4 x i16> [[SRC]] to <vscale x 8 x i8>
// CHECK-IR-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vreinterpret_v_u16m1_u8m1(vuint16m1_t src) {
  return __riscv_vreinterpret_v_u16m1_u8m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 16 x i8> @test_vreinterpret_v_u16m2_u8m2
// CHECK-IR-SAME: (<vscale x 8 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i16> [[SRC]] to <vscale x 16 x i8>
// CHECK-IR-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_vreinterpret_v_u16m2_u8m2(vuint16m2_t src) {
  return __riscv_vreinterpret_v_u16m2_u8m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 32 x i8> @test_vreinterpret_v_u16m4_u8m4
// CHECK-IR-SAME: (<vscale x 16 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 16 x i16> [[SRC]] to <vscale x 32 x i8>
// CHECK-IR-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vuint8m4_t test_vreinterpret_v_u16m4_u8m4(vuint16m4_t src) {
  return __riscv_vreinterpret_v_u16m4_u8m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 64 x i8> @test_vreinterpret_v_u16m8_u8m8
// CHECK-IR-SAME: (<vscale x 32 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 32 x i16> [[SRC]] to <vscale x 64 x i8>
// CHECK-IR-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vuint8m8_t test_vreinterpret_v_u16m8_u8m8(vuint16m8_t src) {
  return __riscv_vreinterpret_v_u16m8_u8m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 2 x i32> @test_vreinterpret_v_i16m1_i32m1
// CHECK-IR-SAME: (<vscale x 4 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 4 x i16> [[SRC]] to <vscale x 2 x i32>
// CHECK-IR-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vreinterpret_v_i16m1_i32m1(vint16m1_t src) {
  return __riscv_vreinterpret_v_i16m1_i32m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 4 x i32> @test_vreinterpret_v_i16m2_i32m2
// CHECK-IR-SAME: (<vscale x 8 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i16> [[SRC]] to <vscale x 4 x i32>
// CHECK-IR-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vreinterpret_v_i16m2_i32m2(vint16m2_t src) {
  return __riscv_vreinterpret_v_i16m2_i32m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i32> @test_vreinterpret_v_i16m4_i32m4
// CHECK-IR-SAME: (<vscale x 16 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 16 x i16> [[SRC]] to <vscale x 8 x i32>
// CHECK-IR-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vreinterpret_v_i16m4_i32m4(vint16m4_t src) {
  return __riscv_vreinterpret_v_i16m4_i32m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 16 x i32> @test_vreinterpret_v_i16m8_i32m8
// CHECK-IR-SAME: (<vscale x 32 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 32 x i16> [[SRC]] to <vscale x 16 x i32>
// CHECK-IR-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vreinterpret_v_i16m8_i32m8(vint16m8_t src) {
  return __riscv_vreinterpret_v_i16m8_i32m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 2 x i32> @test_vreinterpret_v_u16m1_u32m1
// CHECK-IR-SAME: (<vscale x 4 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 4 x i16> [[SRC]] to <vscale x 2 x i32>
// CHECK-IR-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vreinterpret_v_u16m1_u32m1(vuint16m1_t src) {
  return __riscv_vreinterpret_v_u16m1_u32m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 4 x i32> @test_vreinterpret_v_u16m2_u32m2
// CHECK-IR-SAME: (<vscale x 8 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i16> [[SRC]] to <vscale x 4 x i32>
// CHECK-IR-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vreinterpret_v_u16m2_u32m2(vuint16m2_t src) {
  return __riscv_vreinterpret_v_u16m2_u32m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i32> @test_vreinterpret_v_u16m4_u32m4
// CHECK-IR-SAME: (<vscale x 16 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 16 x i16> [[SRC]] to <vscale x 8 x i32>
// CHECK-IR-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vreinterpret_v_u16m4_u32m4(vuint16m4_t src) {
  return __riscv_vreinterpret_v_u16m4_u32m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 16 x i32> @test_vreinterpret_v_u16m8_u32m8
// CHECK-IR-SAME: (<vscale x 32 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 32 x i16> [[SRC]] to <vscale x 16 x i32>
// CHECK-IR-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vreinterpret_v_u16m8_u32m8(vuint16m8_t src) {
  return __riscv_vreinterpret_v_u16m8_u32m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 1 x i64> @test_vreinterpret_v_i16m1_i64m1
// CHECK-IR-SAME: (<vscale x 4 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 4 x i16> [[SRC]] to <vscale x 1 x i64>
// CHECK-IR-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vreinterpret_v_i16m1_i64m1(vint16m1_t src) {
  return __riscv_vreinterpret_v_i16m1_i64m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 2 x i64> @test_vreinterpret_v_i16m2_i64m2
// CHECK-IR-SAME: (<vscale x 8 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i16> [[SRC]] to <vscale x 2 x i64>
// CHECK-IR-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vreinterpret_v_i16m2_i64m2(vint16m2_t src) {
  return __riscv_vreinterpret_v_i16m2_i64m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 4 x i64> @test_vreinterpret_v_i16m4_i64m4
// CHECK-IR-SAME: (<vscale x 16 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 16 x i16> [[SRC]] to <vscale x 4 x i64>
// CHECK-IR-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vreinterpret_v_i16m4_i64m4(vint16m4_t src) {
  return __riscv_vreinterpret_v_i16m4_i64m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i64> @test_vreinterpret_v_i16m8_i64m8
// CHECK-IR-SAME: (<vscale x 32 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 32 x i16> [[SRC]] to <vscale x 8 x i64>
// CHECK-IR-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vreinterpret_v_i16m8_i64m8(vint16m8_t src) {
  return __riscv_vreinterpret_v_i16m8_i64m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 1 x i64> @test_vreinterpret_v_u16m1_u64m1
// CHECK-IR-SAME: (<vscale x 4 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 4 x i16> [[SRC]] to <vscale x 1 x i64>
// CHECK-IR-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vreinterpret_v_u16m1_u64m1(vuint16m1_t src) {
  return __riscv_vreinterpret_v_u16m1_u64m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 2 x i64> @test_vreinterpret_v_u16m2_u64m2
// CHECK-IR-SAME: (<vscale x 8 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i16> [[SRC]] to <vscale x 2 x i64>
// CHECK-IR-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vreinterpret_v_u16m2_u64m2(vuint16m2_t src) {
  return __riscv_vreinterpret_v_u16m2_u64m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 4 x i64> @test_vreinterpret_v_u16m4_u64m4
// CHECK-IR-SAME: (<vscale x 16 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 16 x i16> [[SRC]] to <vscale x 4 x i64>
// CHECK-IR-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vreinterpret_v_u16m4_u64m4(vuint16m4_t src) {
  return __riscv_vreinterpret_v_u16m4_u64m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i64> @test_vreinterpret_v_u16m8_u64m8
// CHECK-IR-SAME: (<vscale x 32 x i16> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 32 x i16> [[SRC]] to <vscale x 8 x i64>
// CHECK-IR-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vreinterpret_v_u16m8_u64m8(vuint16m8_t src) {
  return __riscv_vreinterpret_v_u16m8_u64m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i8> @test_vreinterpret_v_i32m1_i8m1
// CHECK-IR-SAME: (<vscale x 2 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 2 x i32> [[SRC]] to <vscale x 8 x i8>
// CHECK-IR-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vreinterpret_v_i32m1_i8m1(vint32m1_t src) {
  return __riscv_vreinterpret_v_i32m1_i8m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 16 x i8> @test_vreinterpret_v_i32m2_i8m2
// CHECK-IR-SAME: (<vscale x 4 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 4 x i32> [[SRC]] to <vscale x 16 x i8>
// CHECK-IR-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vint8m2_t test_vreinterpret_v_i32m2_i8m2(vint32m2_t src) {
  return __riscv_vreinterpret_v_i32m2_i8m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 32 x i8> @test_vreinterpret_v_i32m4_i8m4
// CHECK-IR-SAME: (<vscale x 8 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i32> [[SRC]] to <vscale x 32 x i8>
// CHECK-IR-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vint8m4_t test_vreinterpret_v_i32m4_i8m4(vint32m4_t src) {
  return __riscv_vreinterpret_v_i32m4_i8m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 64 x i8> @test_vreinterpret_v_i32m8_i8m8
// CHECK-IR-SAME: (<vscale x 16 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 16 x i32> [[SRC]] to <vscale x 64 x i8>
// CHECK-IR-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vint8m8_t test_vreinterpret_v_i32m8_i8m8(vint32m8_t src) {
  return __riscv_vreinterpret_v_i32m8_i8m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i8> @test_vreinterpret_v_u32m1_u8m1
// CHECK-IR-SAME: (<vscale x 2 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 2 x i32> [[SRC]] to <vscale x 8 x i8>
// CHECK-IR-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vreinterpret_v_u32m1_u8m1(vuint32m1_t src) {
  return __riscv_vreinterpret_v_u32m1_u8m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 16 x i8> @test_vreinterpret_v_u32m2_u8m2
// CHECK-IR-SAME: (<vscale x 4 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 4 x i32> [[SRC]] to <vscale x 16 x i8>
// CHECK-IR-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_vreinterpret_v_u32m2_u8m2(vuint32m2_t src) {
  return __riscv_vreinterpret_v_u32m2_u8m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 32 x i8> @test_vreinterpret_v_u32m4_u8m4
// CHECK-IR-SAME: (<vscale x 8 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i32> [[SRC]] to <vscale x 32 x i8>
// CHECK-IR-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vuint8m4_t test_vreinterpret_v_u32m4_u8m4(vuint32m4_t src) {
  return __riscv_vreinterpret_v_u32m4_u8m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 64 x i8> @test_vreinterpret_v_u32m8_u8m8
// CHECK-IR-SAME: (<vscale x 16 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 16 x i32> [[SRC]] to <vscale x 64 x i8>
// CHECK-IR-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vuint8m8_t test_vreinterpret_v_u32m8_u8m8(vuint32m8_t src) {
  return __riscv_vreinterpret_v_u32m8_u8m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 4 x i16> @test_vreinterpret_v_i32m1_i16m1
// CHECK-IR-SAME: (<vscale x 2 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 2 x i32> [[SRC]] to <vscale x 4 x i16>
// CHECK-IR-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vreinterpret_v_i32m1_i16m1(vint32m1_t src) {
  return __riscv_vreinterpret_v_i32m1_i16m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i16> @test_vreinterpret_v_i32m2_i16m2
// CHECK-IR-SAME: (<vscale x 4 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 4 x i32> [[SRC]] to <vscale x 8 x i16>
// CHECK-IR-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vreinterpret_v_i32m2_i16m2(vint32m2_t src) {
  return __riscv_vreinterpret_v_i32m2_i16m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 16 x i16> @test_vreinterpret_v_i32m4_i16m4
// CHECK-IR-SAME: (<vscale x 8 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i32> [[SRC]] to <vscale x 16 x i16>
// CHECK-IR-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vreinterpret_v_i32m4_i16m4(vint32m4_t src) {
  return __riscv_vreinterpret_v_i32m4_i16m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 32 x i16> @test_vreinterpret_v_i32m8_i16m8
// CHECK-IR-SAME: (<vscale x 16 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 16 x i32> [[SRC]] to <vscale x 32 x i16>
// CHECK-IR-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vint16m8_t test_vreinterpret_v_i32m8_i16m8(vint32m8_t src) {
  return __riscv_vreinterpret_v_i32m8_i16m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 4 x i16> @test_vreinterpret_v_u32m1_u16m1
// CHECK-IR-SAME: (<vscale x 2 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 2 x i32> [[SRC]] to <vscale x 4 x i16>
// CHECK-IR-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vreinterpret_v_u32m1_u16m1(vuint32m1_t src) {
  return __riscv_vreinterpret_v_u32m1_u16m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i16> @test_vreinterpret_v_u32m2_u16m2
// CHECK-IR-SAME: (<vscale x 4 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 4 x i32> [[SRC]] to <vscale x 8 x i16>
// CHECK-IR-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vreinterpret_v_u32m2_u16m2(vuint32m2_t src) {
  return __riscv_vreinterpret_v_u32m2_u16m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 16 x i16> @test_vreinterpret_v_u32m4_u16m4
// CHECK-IR-SAME: (<vscale x 8 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i32> [[SRC]] to <vscale x 16 x i16>
// CHECK-IR-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vreinterpret_v_u32m4_u16m4(vuint32m4_t src) {
  return __riscv_vreinterpret_v_u32m4_u16m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 32 x i16> @test_vreinterpret_v_u32m8_u16m8
// CHECK-IR-SAME: (<vscale x 16 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 16 x i32> [[SRC]] to <vscale x 32 x i16>
// CHECK-IR-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_vreinterpret_v_u32m8_u16m8(vuint32m8_t src) {
  return __riscv_vreinterpret_v_u32m8_u16m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 1 x i64> @test_vreinterpret_v_i32m1_i64m1
// CHECK-IR-SAME: (<vscale x 2 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 2 x i32> [[SRC]] to <vscale x 1 x i64>
// CHECK-IR-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vreinterpret_v_i32m1_i64m1(vint32m1_t src) {
  return __riscv_vreinterpret_v_i32m1_i64m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 2 x i64> @test_vreinterpret_v_i32m2_i64m2
// CHECK-IR-SAME: (<vscale x 4 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 4 x i32> [[SRC]] to <vscale x 2 x i64>
// CHECK-IR-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vreinterpret_v_i32m2_i64m2(vint32m2_t src) {
  return __riscv_vreinterpret_v_i32m2_i64m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 4 x i64> @test_vreinterpret_v_i32m4_i64m4
// CHECK-IR-SAME: (<vscale x 8 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i32> [[SRC]] to <vscale x 4 x i64>
// CHECK-IR-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vreinterpret_v_i32m4_i64m4(vint32m4_t src) {
  return __riscv_vreinterpret_v_i32m4_i64m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i64> @test_vreinterpret_v_i32m8_i64m8
// CHECK-IR-SAME: (<vscale x 16 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 16 x i32> [[SRC]] to <vscale x 8 x i64>
// CHECK-IR-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vreinterpret_v_i32m8_i64m8(vint32m8_t src) {
  return __riscv_vreinterpret_v_i32m8_i64m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 1 x i64> @test_vreinterpret_v_u32m1_u64m1
// CHECK-IR-SAME: (<vscale x 2 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 2 x i32> [[SRC]] to <vscale x 1 x i64>
// CHECK-IR-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vreinterpret_v_u32m1_u64m1(vuint32m1_t src) {
  return __riscv_vreinterpret_v_u32m1_u64m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 2 x i64> @test_vreinterpret_v_u32m2_u64m2
// CHECK-IR-SAME: (<vscale x 4 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 4 x i32> [[SRC]] to <vscale x 2 x i64>
// CHECK-IR-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vreinterpret_v_u32m2_u64m2(vuint32m2_t src) {
  return __riscv_vreinterpret_v_u32m2_u64m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 4 x i64> @test_vreinterpret_v_u32m4_u64m4
// CHECK-IR-SAME: (<vscale x 8 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i32> [[SRC]] to <vscale x 4 x i64>
// CHECK-IR-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vreinterpret_v_u32m4_u64m4(vuint32m4_t src) {
  return __riscv_vreinterpret_v_u32m4_u64m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i64> @test_vreinterpret_v_u32m8_u64m8
// CHECK-IR-SAME: (<vscale x 16 x i32> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 16 x i32> [[SRC]] to <vscale x 8 x i64>
// CHECK-IR-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vreinterpret_v_u32m8_u64m8(vuint32m8_t src) {
  return __riscv_vreinterpret_v_u32m8_u64m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i8> @test_vreinterpret_v_i64m1_i8m1
// CHECK-IR-SAME: (<vscale x 1 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 1 x i64> [[SRC]] to <vscale x 8 x i8>
// CHECK-IR-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vreinterpret_v_i64m1_i8m1(vint64m1_t src) {
  return __riscv_vreinterpret_v_i64m1_i8m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 16 x i8> @test_vreinterpret_v_i64m2_i8m2
// CHECK-IR-SAME: (<vscale x 2 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 2 x i64> [[SRC]] to <vscale x 16 x i8>
// CHECK-IR-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vint8m2_t test_vreinterpret_v_i64m2_i8m2(vint64m2_t src) {
  return __riscv_vreinterpret_v_i64m2_i8m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 32 x i8> @test_vreinterpret_v_i64m4_i8m4
// CHECK-IR-SAME: (<vscale x 4 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 4 x i64> [[SRC]] to <vscale x 32 x i8>
// CHECK-IR-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vint8m4_t test_vreinterpret_v_i64m4_i8m4(vint64m4_t src) {
  return __riscv_vreinterpret_v_i64m4_i8m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 64 x i8> @test_vreinterpret_v_i64m8_i8m8
// CHECK-IR-SAME: (<vscale x 8 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i64> [[SRC]] to <vscale x 64 x i8>
// CHECK-IR-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vint8m8_t test_vreinterpret_v_i64m8_i8m8(vint64m8_t src) {
  return __riscv_vreinterpret_v_i64m8_i8m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i8> @test_vreinterpret_v_u64m1_u8m1
// CHECK-IR-SAME: (<vscale x 1 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 1 x i64> [[SRC]] to <vscale x 8 x i8>
// CHECK-IR-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vreinterpret_v_u64m1_u8m1(vuint64m1_t src) {
  return __riscv_vreinterpret_v_u64m1_u8m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 16 x i8> @test_vreinterpret_v_u64m2_u8m2
// CHECK-IR-SAME: (<vscale x 2 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 2 x i64> [[SRC]] to <vscale x 16 x i8>
// CHECK-IR-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_vreinterpret_v_u64m2_u8m2(vuint64m2_t src) {
  return __riscv_vreinterpret_v_u64m2_u8m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 32 x i8> @test_vreinterpret_v_u64m4_u8m4
// CHECK-IR-SAME: (<vscale x 4 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 4 x i64> [[SRC]] to <vscale x 32 x i8>
// CHECK-IR-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vuint8m4_t test_vreinterpret_v_u64m4_u8m4(vuint64m4_t src) {
  return __riscv_vreinterpret_v_u64m4_u8m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 64 x i8> @test_vreinterpret_v_u64m8_u8m8
// CHECK-IR-SAME: (<vscale x 8 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i64> [[SRC]] to <vscale x 64 x i8>
// CHECK-IR-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vuint8m8_t test_vreinterpret_v_u64m8_u8m8(vuint64m8_t src) {
  return __riscv_vreinterpret_v_u64m8_u8m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 4 x i16> @test_vreinterpret_v_i64m1_i16m1
// CHECK-IR-SAME: (<vscale x 1 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 1 x i64> [[SRC]] to <vscale x 4 x i16>
// CHECK-IR-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vreinterpret_v_i64m1_i16m1(vint64m1_t src) {
  return __riscv_vreinterpret_v_i64m1_i16m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i16> @test_vreinterpret_v_i64m2_i16m2
// CHECK-IR-SAME: (<vscale x 2 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 2 x i64> [[SRC]] to <vscale x 8 x i16>
// CHECK-IR-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vreinterpret_v_i64m2_i16m2(vint64m2_t src) {
  return __riscv_vreinterpret_v_i64m2_i16m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 16 x i16> @test_vreinterpret_v_i64m4_i16m4
// CHECK-IR-SAME: (<vscale x 4 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 4 x i64> [[SRC]] to <vscale x 16 x i16>
// CHECK-IR-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vreinterpret_v_i64m4_i16m4(vint64m4_t src) {
  return __riscv_vreinterpret_v_i64m4_i16m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 32 x i16> @test_vreinterpret_v_i64m8_i16m8
// CHECK-IR-SAME: (<vscale x 8 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i64> [[SRC]] to <vscale x 32 x i16>
// CHECK-IR-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vint16m8_t test_vreinterpret_v_i64m8_i16m8(vint64m8_t src) {
  return __riscv_vreinterpret_v_i64m8_i16m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 4 x i16> @test_vreinterpret_v_u64m1_u16m1
// CHECK-IR-SAME: (<vscale x 1 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 1 x i64> [[SRC]] to <vscale x 4 x i16>
// CHECK-IR-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vreinterpret_v_u64m1_u16m1(vuint64m1_t src) {
  return __riscv_vreinterpret_v_u64m1_u16m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i16> @test_vreinterpret_v_u64m2_u16m2
// CHECK-IR-SAME: (<vscale x 2 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 2 x i64> [[SRC]] to <vscale x 8 x i16>
// CHECK-IR-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vreinterpret_v_u64m2_u16m2(vuint64m2_t src) {
  return __riscv_vreinterpret_v_u64m2_u16m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 16 x i16> @test_vreinterpret_v_u64m4_u16m4
// CHECK-IR-SAME: (<vscale x 4 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 4 x i64> [[SRC]] to <vscale x 16 x i16>
// CHECK-IR-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vreinterpret_v_u64m4_u16m4(vuint64m4_t src) {
  return __riscv_vreinterpret_v_u64m4_u16m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 32 x i16> @test_vreinterpret_v_u64m8_u16m8
// CHECK-IR-SAME: (<vscale x 8 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i64> [[SRC]] to <vscale x 32 x i16>
// CHECK-IR-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_vreinterpret_v_u64m8_u16m8(vuint64m8_t src) {
  return __riscv_vreinterpret_v_u64m8_u16m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 2 x i32> @test_vreinterpret_v_i64m1_i32m1
// CHECK-IR-SAME: (<vscale x 1 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 1 x i64> [[SRC]] to <vscale x 2 x i32>
// CHECK-IR-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vreinterpret_v_i64m1_i32m1(vint64m1_t src) {
  return __riscv_vreinterpret_v_i64m1_i32m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 4 x i32> @test_vreinterpret_v_i64m2_i32m2
// CHECK-IR-SAME: (<vscale x 2 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 2 x i64> [[SRC]] to <vscale x 4 x i32>
// CHECK-IR-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vreinterpret_v_i64m2_i32m2(vint64m2_t src) {
  return __riscv_vreinterpret_v_i64m2_i32m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i32> @test_vreinterpret_v_i64m4_i32m4
// CHECK-IR-SAME: (<vscale x 4 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 4 x i64> [[SRC]] to <vscale x 8 x i32>
// CHECK-IR-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vreinterpret_v_i64m4_i32m4(vint64m4_t src) {
  return __riscv_vreinterpret_v_i64m4_i32m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 16 x i32> @test_vreinterpret_v_i64m8_i32m8
// CHECK-IR-SAME: (<vscale x 8 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i64> [[SRC]] to <vscale x 16 x i32>
// CHECK-IR-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vreinterpret_v_i64m8_i32m8(vint64m8_t src) {
  return __riscv_vreinterpret_v_i64m8_i32m8(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 2 x i32> @test_vreinterpret_v_u64m1_u32m1
// CHECK-IR-SAME: (<vscale x 1 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 1 x i64> [[SRC]] to <vscale x 2 x i32>
// CHECK-IR-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vreinterpret_v_u64m1_u32m1(vuint64m1_t src) {
  return __riscv_vreinterpret_v_u64m1_u32m1(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 4 x i32> @test_vreinterpret_v_u64m2_u32m2
// CHECK-IR-SAME: (<vscale x 2 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 2 x i64> [[SRC]] to <vscale x 4 x i32>
// CHECK-IR-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vreinterpret_v_u64m2_u32m2(vuint64m2_t src) {
  return __riscv_vreinterpret_v_u64m2_u32m2(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 8 x i32> @test_vreinterpret_v_u64m4_u32m4
// CHECK-IR-SAME: (<vscale x 4 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 4 x i64> [[SRC]] to <vscale x 8 x i32>
// CHECK-IR-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vreinterpret_v_u64m4_u32m4(vuint64m4_t src) {
  return __riscv_vreinterpret_v_u64m4_u32m4(src);
}

// CHECK-IR-LABEL: define dso_local <vscale x 16 x i32> @test_vreinterpret_v_u64m8_u32m8
// CHECK-IR-SAME: (<vscale x 8 x i64> [[SRC:%.*]]) #[[ATTR0]] {
// CHECK-IR-NEXT:  entry:
// CHECK-IR-NEXT:    [[TMP0:%.*]] = bitcast <vscale x 8 x i64> [[SRC]] to <vscale x 16 x i32>
// CHECK-IR-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vreinterpret_v_u64m8_u32m8(vuint64m8_t src) {
  return __riscv_vreinterpret_v_u64m8_u32m8(src);
}
