; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+xtheadvector \
; RUN:   -verify-machineinstrs | FileCheck %s --check-prefixes=CHECK,RV32
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+xtheadvector \
; RUN:   -verify-machineinstrs | FileCheck %s --check-prefixes=CHECK,RV64

declare { <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg2eff.nxv8i8.nxv8i8(
  <vscale x 8 x i8>, <vscale x 8 x i8>,
  <vscale x 8 x i8>*,
  iXLen);

define <vscale x 8 x i8> @intrinsic_vlseg2eff_v_nxv8i8_nxv8i8(<vscale x 8 x i8>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv8i8_nxv8i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV32-NEXT:    th.vlseg2eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv8i8_nxv8i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV64-NEXT:    th.vlseg2eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg2eff.nxv8i8.nxv8i8(
    <vscale x 8 x i8> undef, <vscale x 8 x i8> undef,
    <vscale x 8 x i8>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 8 x i8> %b
}

declare { <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv8i8.nxv8i8(
  <vscale x 8 x i8>, <vscale x 8 x i8>,
  <vscale x 8 x i8>*,
  <vscale x 8 x i1>,
  iXLen);

define <vscale x 8 x i8> @intrinsic_vlseg2eff_mask_v_nxv8i8_nxv8i8(<vscale x 8 x i8>* %0, <vscale x 8 x i8> %1, <vscale x 8 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv8i8_nxv8i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV32-NEXT:    th.vlseg2eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv8i8_nxv8i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV64-NEXT:    th.vlseg2eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv8i8.nxv8i8(
    <vscale x 8 x i8> %1, <vscale x 8 x i8> %1,
    <vscale x 8 x i8>* %0,
    <vscale x 8 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 8 x i8> %b
}

declare { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg3eff.nxv8i8.nxv8i8(
  <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>,
  <vscale x 8 x i8>*,
  iXLen);

define <vscale x 8 x i8> @intrinsic_vlseg3eff_v_nxv8i8_nxv8i8(<vscale x 8 x i8>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_v_nxv8i8_nxv8i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV32-NEXT:    th.vlseg3eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_v_nxv8i8_nxv8i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV64-NEXT:    th.vlseg3eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg3eff.nxv8i8.nxv8i8(
    <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef,
    <vscale x 8 x i8>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 3
  store iXLen %c, iXLen* %2
  ret <vscale x 8 x i8> %b
}

declare { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv8i8.nxv8i8(
  <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>,
  <vscale x 8 x i8>*,
  <vscale x 8 x i1>,
  iXLen);

define <vscale x 8 x i8> @intrinsic_vlseg3eff_mask_v_nxv8i8_nxv8i8(<vscale x 8 x i8>* %0, <vscale x 8 x i8> %1, <vscale x 8 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_mask_v_nxv8i8_nxv8i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV32-NEXT:    th.vlseg3eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_mask_v_nxv8i8_nxv8i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV64-NEXT:    th.vlseg3eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv8i8.nxv8i8(
    <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1,
    <vscale x 8 x i8>* %0,
    <vscale x 8 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 3
  store iXLen %c, iXLen* %4
  ret <vscale x 8 x i8> %b
}

declare { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg4eff.nxv8i8.nxv8i8(
  <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>,
  <vscale x 8 x i8>*,
  iXLen);

define <vscale x 8 x i8> @intrinsic_vlseg4eff_v_nxv8i8_nxv8i8(<vscale x 8 x i8>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_v_nxv8i8_nxv8i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV32-NEXT:    th.vlseg4eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_v_nxv8i8_nxv8i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV64-NEXT:    th.vlseg4eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg4eff.nxv8i8.nxv8i8(
    <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef,
    <vscale x 8 x i8>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 4
  store iXLen %c, iXLen* %2
  ret <vscale x 8 x i8> %b
}

declare { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv8i8.nxv8i8(
  <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>,
  <vscale x 8 x i8>*,
  <vscale x 8 x i1>,
  iXLen);

define <vscale x 8 x i8> @intrinsic_vlseg4eff_mask_v_nxv8i8_nxv8i8(<vscale x 8 x i8>* %0, <vscale x 8 x i8> %1, <vscale x 8 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_mask_v_nxv8i8_nxv8i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV32-NEXT:    th.vlseg4eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_mask_v_nxv8i8_nxv8i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV64-NEXT:    th.vlseg4eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv8i8.nxv8i8(
    <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1,
    <vscale x 8 x i8>* %0,
    <vscale x 8 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 4
  store iXLen %c, iXLen* %4
  ret <vscale x 8 x i8> %b
}

declare { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg5eff.nxv8i8.nxv8i8(
  <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>,
  <vscale x 8 x i8>*,
  iXLen);

define <vscale x 8 x i8> @intrinsic_vlseg5eff_v_nxv8i8_nxv8i8(<vscale x 8 x i8>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg5eff_v_nxv8i8_nxv8i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV32-NEXT:    th.vlseg5eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg5eff_v_nxv8i8_nxv8i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV64-NEXT:    th.vlseg5eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg5eff.nxv8i8.nxv8i8(
    <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef,
    <vscale x 8 x i8>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 5
  store iXLen %c, iXLen* %2
  ret <vscale x 8 x i8> %b
}

declare { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg5eff.mask.nxv8i8.nxv8i8(
  <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>,
  <vscale x 8 x i8>*,
  <vscale x 8 x i1>,
  iXLen);

define <vscale x 8 x i8> @intrinsic_vlseg5eff_mask_v_nxv8i8_nxv8i8(<vscale x 8 x i8>* %0, <vscale x 8 x i8> %1, <vscale x 8 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg5eff_mask_v_nxv8i8_nxv8i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV32-NEXT:    th.vlseg5eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg5eff_mask_v_nxv8i8_nxv8i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV64-NEXT:    th.vlseg5eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg5eff.mask.nxv8i8.nxv8i8(
    <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1,
    <vscale x 8 x i8>* %0,
    <vscale x 8 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 5
  store iXLen %c, iXLen* %4
  ret <vscale x 8 x i8> %b
}

declare { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg6eff.nxv8i8.nxv8i8(
  <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>,
  <vscale x 8 x i8>*,
  iXLen);

define <vscale x 8 x i8> @intrinsic_vlseg6eff_v_nxv8i8_nxv8i8(<vscale x 8 x i8>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg6eff_v_nxv8i8_nxv8i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV32-NEXT:    th.vlseg6eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg6eff_v_nxv8i8_nxv8i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV64-NEXT:    th.vlseg6eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg6eff.nxv8i8.nxv8i8(
    <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef,
    <vscale x 8 x i8>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 6
  store iXLen %c, iXLen* %2
  ret <vscale x 8 x i8> %b
}

declare { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg6eff.mask.nxv8i8.nxv8i8(
  <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>,
  <vscale x 8 x i8>*,
  <vscale x 8 x i1>,
  iXLen);

define <vscale x 8 x i8> @intrinsic_vlseg6eff_mask_v_nxv8i8_nxv8i8(<vscale x 8 x i8>* %0, <vscale x 8 x i8> %1, <vscale x 8 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg6eff_mask_v_nxv8i8_nxv8i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV32-NEXT:    th.vlseg6eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg6eff_mask_v_nxv8i8_nxv8i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV64-NEXT:    th.vlseg6eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg6eff.mask.nxv8i8.nxv8i8(
    <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1,
    <vscale x 8 x i8>* %0,
    <vscale x 8 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 6
  store iXLen %c, iXLen* %4
  ret <vscale x 8 x i8> %b
}

declare { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg7eff.nxv8i8.nxv8i8(
  <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>,
  <vscale x 8 x i8>*,
  iXLen);

define <vscale x 8 x i8> @intrinsic_vlseg7eff_v_nxv8i8_nxv8i8(<vscale x 8 x i8>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg7eff_v_nxv8i8_nxv8i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV32-NEXT:    th.vlseg7eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg7eff_v_nxv8i8_nxv8i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV64-NEXT:    th.vlseg7eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg7eff.nxv8i8.nxv8i8(
    <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef,
    <vscale x 8 x i8>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 7
  store iXLen %c, iXLen* %2
  ret <vscale x 8 x i8> %b
}

declare { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg7eff.mask.nxv8i8.nxv8i8(
  <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>,
  <vscale x 8 x i8>*,
  <vscale x 8 x i1>,
  iXLen);

define <vscale x 8 x i8> @intrinsic_vlseg7eff_mask_v_nxv8i8_nxv8i8(<vscale x 8 x i8>* %0, <vscale x 8 x i8> %1, <vscale x 8 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg7eff_mask_v_nxv8i8_nxv8i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV32-NEXT:    th.vlseg7eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg7eff_mask_v_nxv8i8_nxv8i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV64-NEXT:    th.vlseg7eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg7eff.mask.nxv8i8.nxv8i8(
    <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1,
    <vscale x 8 x i8>* %0,
    <vscale x 8 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 7
  store iXLen %c, iXLen* %4
  ret <vscale x 8 x i8> %b
}

declare { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg8eff.nxv8i8.nxv8i8(
  <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>,
  <vscale x 8 x i8>*,
  iXLen);

define <vscale x 8 x i8> @intrinsic_vlseg8eff_v_nxv8i8_nxv8i8(<vscale x 8 x i8>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg8eff_v_nxv8i8_nxv8i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV32-NEXT:    th.vlseg8eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg8eff_v_nxv8i8_nxv8i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV64-NEXT:    th.vlseg8eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg8eff.nxv8i8.nxv8i8(
    <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef, <vscale x 8 x i8> undef,
    <vscale x 8 x i8>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 8
  store iXLen %c, iXLen* %2
  ret <vscale x 8 x i8> %b
}

declare { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg8eff.mask.nxv8i8.nxv8i8(
  <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>,
  <vscale x 8 x i8>*,
  <vscale x 8 x i1>,
  iXLen);

define <vscale x 8 x i8> @intrinsic_vlseg8eff_mask_v_nxv8i8_nxv8i8(<vscale x 8 x i8>* %0, <vscale x 8 x i8> %1, <vscale x 8 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg8eff_mask_v_nxv8i8_nxv8i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v8
; RV32-NEXT:    th.vmv.v.v v14, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV32-NEXT:    th.vlseg8eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg8eff_mask_v_nxv8i8_nxv8i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v8
; RV64-NEXT:    th.vmv.v.v v14, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e8, m1, d1
; RV64-NEXT:    th.vlseg8eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } @llvm.riscv.th.vlseg8eff.mask.nxv8i8.nxv8i8(
    <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1, <vscale x 8 x i8> %1,
    <vscale x 8 x i8>* %0,
    <vscale x 8 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen } %a, 8
  store iXLen %c, iXLen* %4
  ret <vscale x 8 x i8> %b
}

declare { <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } @llvm.riscv.th.vlseg2eff.nxv16i8.nxv16i8(
  <vscale x 16 x i8>, <vscale x 16 x i8>,
  <vscale x 16 x i8>*,
  iXLen);

define <vscale x 16 x i8> @intrinsic_vlseg2eff_v_nxv16i8_nxv16i8(<vscale x 16 x i8>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv16i8_nxv16i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e8, m2, d1
; RV32-NEXT:    th.vlseg2eff.v v6, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv16i8_nxv16i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e8, m2, d1
; RV64-NEXT:    th.vlseg2eff.v v6, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } @llvm.riscv.th.vlseg2eff.nxv16i8.nxv16i8(
    <vscale x 16 x i8> undef, <vscale x 16 x i8> undef,
    <vscale x 16 x i8>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 16 x i8> %b
}

declare { <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv16i8.nxv16i8(
  <vscale x 16 x i8>, <vscale x 16 x i8>,
  <vscale x 16 x i8>*,
  <vscale x 16 x i1>,
  iXLen);

define <vscale x 16 x i8> @intrinsic_vlseg2eff_mask_v_nxv16i8_nxv16i8(<vscale x 16 x i8>* %0, <vscale x 16 x i8> %1, <vscale x 16 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv16i8_nxv16i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v6, v8
; RV32-NEXT:    th.vmv.v.v v7, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e8, m2, d1
; RV32-NEXT:    th.vlseg2eff.v v6, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv16i8_nxv16i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v6, v8
; RV64-NEXT:    th.vmv.v.v v7, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e8, m2, d1
; RV64-NEXT:    th.vlseg2eff.v v6, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv16i8.nxv16i8(
    <vscale x 16 x i8> %1, <vscale x 16 x i8> %1,
    <vscale x 16 x i8>* %0,
    <vscale x 16 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 16 x i8> %b
}

declare { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } @llvm.riscv.th.vlseg3eff.nxv16i8.nxv16i8(
  <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>,
  <vscale x 16 x i8>*,
  iXLen);

define <vscale x 16 x i8> @intrinsic_vlseg3eff_v_nxv16i8_nxv16i8(<vscale x 16 x i8>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_v_nxv16i8_nxv16i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e8, m2, d1
; RV32-NEXT:    th.vlseg3eff.v v6, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_v_nxv16i8_nxv16i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e8, m2, d1
; RV64-NEXT:    th.vlseg3eff.v v6, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } @llvm.riscv.th.vlseg3eff.nxv16i8.nxv16i8(
    <vscale x 16 x i8> undef, <vscale x 16 x i8> undef, <vscale x 16 x i8> undef,
    <vscale x 16 x i8>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } %a, 3
  store iXLen %c, iXLen* %2
  ret <vscale x 16 x i8> %b
}

declare { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv16i8.nxv16i8(
  <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>,
  <vscale x 16 x i8>*,
  <vscale x 16 x i1>,
  iXLen);

define <vscale x 16 x i8> @intrinsic_vlseg3eff_mask_v_nxv16i8_nxv16i8(<vscale x 16 x i8>* %0, <vscale x 16 x i8> %1, <vscale x 16 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_mask_v_nxv16i8_nxv16i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v6, v8
; RV32-NEXT:    th.vmv.v.v v7, v9
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e8, m2, d1
; RV32-NEXT:    th.vlseg3eff.v v6, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_mask_v_nxv16i8_nxv16i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v6, v8
; RV64-NEXT:    th.vmv.v.v v7, v9
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e8, m2, d1
; RV64-NEXT:    th.vlseg3eff.v v6, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv16i8.nxv16i8(
    <vscale x 16 x i8> %1, <vscale x 16 x i8> %1, <vscale x 16 x i8> %1,
    <vscale x 16 x i8>* %0,
    <vscale x 16 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } %a, 3
  store iXLen %c, iXLen* %4
  ret <vscale x 16 x i8> %b
}

declare { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } @llvm.riscv.th.vlseg4eff.nxv16i8.nxv16i8(
  <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>,
  <vscale x 16 x i8>*,
  iXLen);

define <vscale x 16 x i8> @intrinsic_vlseg4eff_v_nxv16i8_nxv16i8(<vscale x 16 x i8>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_v_nxv16i8_nxv16i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e8, m2, d1
; RV32-NEXT:    th.vlseg4eff.v v6, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_v_nxv16i8_nxv16i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e8, m2, d1
; RV64-NEXT:    th.vlseg4eff.v v6, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } @llvm.riscv.th.vlseg4eff.nxv16i8.nxv16i8(
    <vscale x 16 x i8> undef, <vscale x 16 x i8> undef, <vscale x 16 x i8> undef, <vscale x 16 x i8> undef,
    <vscale x 16 x i8>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } %a, 4
  store iXLen %c, iXLen* %2
  ret <vscale x 16 x i8> %b
}

declare { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv16i8.nxv16i8(
  <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>,
  <vscale x 16 x i8>*,
  <vscale x 16 x i1>,
  iXLen);

define <vscale x 16 x i8> @intrinsic_vlseg4eff_mask_v_nxv16i8_nxv16i8(<vscale x 16 x i8>* %0, <vscale x 16 x i8> %1, <vscale x 16 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_mask_v_nxv16i8_nxv16i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v6, v8
; RV32-NEXT:    th.vmv.v.v v7, v9
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v9
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e8, m2, d1
; RV32-NEXT:    th.vlseg4eff.v v6, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_mask_v_nxv16i8_nxv16i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v6, v8
; RV64-NEXT:    th.vmv.v.v v7, v9
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v9
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e8, m2, d1
; RV64-NEXT:    th.vlseg4eff.v v6, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv16i8.nxv16i8(
    <vscale x 16 x i8> %1, <vscale x 16 x i8> %1, <vscale x 16 x i8> %1, <vscale x 16 x i8> %1,
    <vscale x 16 x i8>* %0,
    <vscale x 16 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, <vscale x 16 x i8>, iXLen } %a, 4
  store iXLen %c, iXLen* %4
  ret <vscale x 16 x i8> %b
}

declare { <vscale x 32 x i8>, <vscale x 32 x i8>, iXLen } @llvm.riscv.th.vlseg2eff.nxv32i8.nxv32i8(
  <vscale x 32 x i8>, <vscale x 32 x i8>,
  <vscale x 32 x i8>*,
  iXLen);

define <vscale x 32 x i8> @intrinsic_vlseg2eff_v_nxv32i8_nxv32i8(<vscale x 32 x i8>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv32i8_nxv32i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e8, m4, d1
; RV32-NEXT:    th.vlseg2eff.v v4, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv32i8_nxv32i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e8, m4, d1
; RV64-NEXT:    th.vlseg2eff.v v4, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 32 x i8>, <vscale x 32 x i8>, iXLen } @llvm.riscv.th.vlseg2eff.nxv32i8.nxv32i8(
    <vscale x 32 x i8> undef, <vscale x 32 x i8> undef,
    <vscale x 32 x i8>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 32 x i8>, <vscale x 32 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 32 x i8>, <vscale x 32 x i8>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 32 x i8> %b
}

declare { <vscale x 32 x i8>, <vscale x 32 x i8>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv32i8.nxv32i8(
  <vscale x 32 x i8>, <vscale x 32 x i8>,
  <vscale x 32 x i8>*,
  <vscale x 32 x i1>,
  iXLen);

define <vscale x 32 x i8> @intrinsic_vlseg2eff_mask_v_nxv32i8_nxv32i8(<vscale x 32 x i8>* %0, <vscale x 32 x i8> %1, <vscale x 32 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv32i8_nxv32i8:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v4, v8
; RV32-NEXT:    th.vmv.v.v v5, v9
; RV32-NEXT:    th.vmv.v.v v6, v10
; RV32-NEXT:    th.vmv.v.v v7, v11
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e8, m4, d1
; RV32-NEXT:    th.vlseg2eff.v v4, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv32i8_nxv32i8:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v4, v8
; RV64-NEXT:    th.vmv.v.v v5, v9
; RV64-NEXT:    th.vmv.v.v v6, v10
; RV64-NEXT:    th.vmv.v.v v7, v11
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e8, m4, d1
; RV64-NEXT:    th.vlseg2eff.v v4, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 32 x i8>, <vscale x 32 x i8>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv32i8.nxv32i8(
    <vscale x 32 x i8> %1, <vscale x 32 x i8> %1,
    <vscale x 32 x i8>* %0,
    <vscale x 32 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 32 x i8>, <vscale x 32 x i8>, iXLen } %a, 1
  %c = extractvalue { <vscale x 32 x i8>, <vscale x 32 x i8>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 32 x i8> %b
}

declare { <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg2eff.nxv4i16.nxv4i16(
  <vscale x 4 x i16>, <vscale x 4 x i16>,
  <vscale x 4 x i16>*,
  iXLen);

define <vscale x 4 x i16> @intrinsic_vlseg2eff_v_nxv4i16_nxv4i16(<vscale x 4 x i16>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv4i16_nxv4i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg2eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv4i16_nxv4i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg2eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg2eff.nxv4i16.nxv4i16(
    <vscale x 4 x i16> undef, <vscale x 4 x i16> undef,
    <vscale x 4 x i16>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x i16> %b
}

declare { <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv4i16.nxv4i16(
  <vscale x 4 x i16>, <vscale x 4 x i16>,
  <vscale x 4 x i16>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x i16> @intrinsic_vlseg2eff_mask_v_nxv4i16_nxv4i16(<vscale x 4 x i16>* %0, <vscale x 4 x i16> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv4i16_nxv4i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg2eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv4i16_nxv4i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg2eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv4i16.nxv4i16(
    <vscale x 4 x i16> %1, <vscale x 4 x i16> %1,
    <vscale x 4 x i16>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x i16> %b
}

declare { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg3eff.nxv4i16.nxv4i16(
  <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>,
  <vscale x 4 x i16>*,
  iXLen);

define <vscale x 4 x i16> @intrinsic_vlseg3eff_v_nxv4i16_nxv4i16(<vscale x 4 x i16>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_v_nxv4i16_nxv4i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg3eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_v_nxv4i16_nxv4i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg3eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg3eff.nxv4i16.nxv4i16(
    <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef,
    <vscale x 4 x i16>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 3
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x i16> %b
}

declare { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv4i16.nxv4i16(
  <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>,
  <vscale x 4 x i16>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x i16> @intrinsic_vlseg3eff_mask_v_nxv4i16_nxv4i16(<vscale x 4 x i16>* %0, <vscale x 4 x i16> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_mask_v_nxv4i16_nxv4i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg3eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_mask_v_nxv4i16_nxv4i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg3eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv4i16.nxv4i16(
    <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1,
    <vscale x 4 x i16>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 3
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x i16> %b
}

declare { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg4eff.nxv4i16.nxv4i16(
  <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>,
  <vscale x 4 x i16>*,
  iXLen);

define <vscale x 4 x i16> @intrinsic_vlseg4eff_v_nxv4i16_nxv4i16(<vscale x 4 x i16>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_v_nxv4i16_nxv4i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg4eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_v_nxv4i16_nxv4i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg4eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg4eff.nxv4i16.nxv4i16(
    <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef,
    <vscale x 4 x i16>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 4
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x i16> %b
}

declare { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv4i16.nxv4i16(
  <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>,
  <vscale x 4 x i16>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x i16> @intrinsic_vlseg4eff_mask_v_nxv4i16_nxv4i16(<vscale x 4 x i16>* %0, <vscale x 4 x i16> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_mask_v_nxv4i16_nxv4i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg4eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_mask_v_nxv4i16_nxv4i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg4eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv4i16.nxv4i16(
    <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1,
    <vscale x 4 x i16>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 4
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x i16> %b
}

declare { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg5eff.nxv4i16.nxv4i16(
  <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>,
  <vscale x 4 x i16>*,
  iXLen);

define <vscale x 4 x i16> @intrinsic_vlseg5eff_v_nxv4i16_nxv4i16(<vscale x 4 x i16>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg5eff_v_nxv4i16_nxv4i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg5eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg5eff_v_nxv4i16_nxv4i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg5eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg5eff.nxv4i16.nxv4i16(
    <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef,
    <vscale x 4 x i16>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 5
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x i16> %b
}

declare { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg5eff.mask.nxv4i16.nxv4i16(
  <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>,
  <vscale x 4 x i16>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x i16> @intrinsic_vlseg5eff_mask_v_nxv4i16_nxv4i16(<vscale x 4 x i16>* %0, <vscale x 4 x i16> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg5eff_mask_v_nxv4i16_nxv4i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg5eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg5eff_mask_v_nxv4i16_nxv4i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg5eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg5eff.mask.nxv4i16.nxv4i16(
    <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1,
    <vscale x 4 x i16>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 5
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x i16> %b
}

declare { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg6eff.nxv4i16.nxv4i16(
  <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>,
  <vscale x 4 x i16>*,
  iXLen);

define <vscale x 4 x i16> @intrinsic_vlseg6eff_v_nxv4i16_nxv4i16(<vscale x 4 x i16>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg6eff_v_nxv4i16_nxv4i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg6eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg6eff_v_nxv4i16_nxv4i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg6eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg6eff.nxv4i16.nxv4i16(
    <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef,
    <vscale x 4 x i16>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 6
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x i16> %b
}

declare { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg6eff.mask.nxv4i16.nxv4i16(
  <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>,
  <vscale x 4 x i16>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x i16> @intrinsic_vlseg6eff_mask_v_nxv4i16_nxv4i16(<vscale x 4 x i16>* %0, <vscale x 4 x i16> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg6eff_mask_v_nxv4i16_nxv4i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg6eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg6eff_mask_v_nxv4i16_nxv4i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg6eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg6eff.mask.nxv4i16.nxv4i16(
    <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1,
    <vscale x 4 x i16>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 6
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x i16> %b
}

declare { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg7eff.nxv4i16.nxv4i16(
  <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>,
  <vscale x 4 x i16>*,
  iXLen);

define <vscale x 4 x i16> @intrinsic_vlseg7eff_v_nxv4i16_nxv4i16(<vscale x 4 x i16>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg7eff_v_nxv4i16_nxv4i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg7eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg7eff_v_nxv4i16_nxv4i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg7eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg7eff.nxv4i16.nxv4i16(
    <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef,
    <vscale x 4 x i16>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 7
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x i16> %b
}

declare { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg7eff.mask.nxv4i16.nxv4i16(
  <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>,
  <vscale x 4 x i16>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x i16> @intrinsic_vlseg7eff_mask_v_nxv4i16_nxv4i16(<vscale x 4 x i16>* %0, <vscale x 4 x i16> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg7eff_mask_v_nxv4i16_nxv4i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg7eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg7eff_mask_v_nxv4i16_nxv4i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg7eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg7eff.mask.nxv4i16.nxv4i16(
    <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1,
    <vscale x 4 x i16>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 7
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x i16> %b
}

declare { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg8eff.nxv4i16.nxv4i16(
  <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>,
  <vscale x 4 x i16>*,
  iXLen);

define <vscale x 4 x i16> @intrinsic_vlseg8eff_v_nxv4i16_nxv4i16(<vscale x 4 x i16>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg8eff_v_nxv4i16_nxv4i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg8eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg8eff_v_nxv4i16_nxv4i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg8eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg8eff.nxv4i16.nxv4i16(
    <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef, <vscale x 4 x i16> undef,
    <vscale x 4 x i16>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 8
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x i16> %b
}

declare { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg8eff.mask.nxv4i16.nxv4i16(
  <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>,
  <vscale x 4 x i16>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x i16> @intrinsic_vlseg8eff_mask_v_nxv4i16_nxv4i16(<vscale x 4 x i16>* %0, <vscale x 4 x i16> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg8eff_mask_v_nxv4i16_nxv4i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v8
; RV32-NEXT:    th.vmv.v.v v14, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg8eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg8eff_mask_v_nxv4i16_nxv4i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v8
; RV64-NEXT:    th.vmv.v.v v14, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg8eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } @llvm.riscv.th.vlseg8eff.mask.nxv4i16.nxv4i16(
    <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1, <vscale x 4 x i16> %1,
    <vscale x 4 x i16>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, <vscale x 4 x i16>, iXLen } %a, 8
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x i16> %b
}

declare { <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } @llvm.riscv.th.vlseg2eff.nxv8i16.nxv8i16(
  <vscale x 8 x i16>, <vscale x 8 x i16>,
  <vscale x 8 x i16>*,
  iXLen);

define <vscale x 8 x i16> @intrinsic_vlseg2eff_v_nxv8i16_nxv8i16(<vscale x 8 x i16>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv8i16_nxv8i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV32-NEXT:    th.vlseg2eff.v v6, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv8i16_nxv8i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV64-NEXT:    th.vlseg2eff.v v6, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } @llvm.riscv.th.vlseg2eff.nxv8i16.nxv8i16(
    <vscale x 8 x i16> undef, <vscale x 8 x i16> undef,
    <vscale x 8 x i16>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 8 x i16> %b
}

declare { <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv8i16.nxv8i16(
  <vscale x 8 x i16>, <vscale x 8 x i16>,
  <vscale x 8 x i16>*,
  <vscale x 8 x i1>,
  iXLen);

define <vscale x 8 x i16> @intrinsic_vlseg2eff_mask_v_nxv8i16_nxv8i16(<vscale x 8 x i16>* %0, <vscale x 8 x i16> %1, <vscale x 8 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv8i16_nxv8i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v6, v8
; RV32-NEXT:    th.vmv.v.v v7, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV32-NEXT:    th.vlseg2eff.v v6, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv8i16_nxv8i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v6, v8
; RV64-NEXT:    th.vmv.v.v v7, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV64-NEXT:    th.vlseg2eff.v v6, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv8i16.nxv8i16(
    <vscale x 8 x i16> %1, <vscale x 8 x i16> %1,
    <vscale x 8 x i16>* %0,
    <vscale x 8 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 8 x i16> %b
}

declare { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } @llvm.riscv.th.vlseg3eff.nxv8i16.nxv8i16(
  <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>,
  <vscale x 8 x i16>*,
  iXLen);

define <vscale x 8 x i16> @intrinsic_vlseg3eff_v_nxv8i16_nxv8i16(<vscale x 8 x i16>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_v_nxv8i16_nxv8i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV32-NEXT:    th.vlseg3eff.v v6, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_v_nxv8i16_nxv8i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV64-NEXT:    th.vlseg3eff.v v6, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } @llvm.riscv.th.vlseg3eff.nxv8i16.nxv8i16(
    <vscale x 8 x i16> undef, <vscale x 8 x i16> undef, <vscale x 8 x i16> undef,
    <vscale x 8 x i16>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } %a, 3
  store iXLen %c, iXLen* %2
  ret <vscale x 8 x i16> %b
}

declare { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv8i16.nxv8i16(
  <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>,
  <vscale x 8 x i16>*,
  <vscale x 8 x i1>,
  iXLen);

define <vscale x 8 x i16> @intrinsic_vlseg3eff_mask_v_nxv8i16_nxv8i16(<vscale x 8 x i16>* %0, <vscale x 8 x i16> %1, <vscale x 8 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_mask_v_nxv8i16_nxv8i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v6, v8
; RV32-NEXT:    th.vmv.v.v v7, v9
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV32-NEXT:    th.vlseg3eff.v v6, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_mask_v_nxv8i16_nxv8i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v6, v8
; RV64-NEXT:    th.vmv.v.v v7, v9
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV64-NEXT:    th.vlseg3eff.v v6, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv8i16.nxv8i16(
    <vscale x 8 x i16> %1, <vscale x 8 x i16> %1, <vscale x 8 x i16> %1,
    <vscale x 8 x i16>* %0,
    <vscale x 8 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } %a, 3
  store iXLen %c, iXLen* %4
  ret <vscale x 8 x i16> %b
}

declare { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } @llvm.riscv.th.vlseg4eff.nxv8i16.nxv8i16(
  <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>,
  <vscale x 8 x i16>*,
  iXLen);

define <vscale x 8 x i16> @intrinsic_vlseg4eff_v_nxv8i16_nxv8i16(<vscale x 8 x i16>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_v_nxv8i16_nxv8i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV32-NEXT:    th.vlseg4eff.v v6, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_v_nxv8i16_nxv8i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV64-NEXT:    th.vlseg4eff.v v6, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } @llvm.riscv.th.vlseg4eff.nxv8i16.nxv8i16(
    <vscale x 8 x i16> undef, <vscale x 8 x i16> undef, <vscale x 8 x i16> undef, <vscale x 8 x i16> undef,
    <vscale x 8 x i16>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } %a, 4
  store iXLen %c, iXLen* %2
  ret <vscale x 8 x i16> %b
}

declare { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv8i16.nxv8i16(
  <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>,
  <vscale x 8 x i16>*,
  <vscale x 8 x i1>,
  iXLen);

define <vscale x 8 x i16> @intrinsic_vlseg4eff_mask_v_nxv8i16_nxv8i16(<vscale x 8 x i16>* %0, <vscale x 8 x i16> %1, <vscale x 8 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_mask_v_nxv8i16_nxv8i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v6, v8
; RV32-NEXT:    th.vmv.v.v v7, v9
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v9
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV32-NEXT:    th.vlseg4eff.v v6, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_mask_v_nxv8i16_nxv8i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v6, v8
; RV64-NEXT:    th.vmv.v.v v7, v9
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v9
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV64-NEXT:    th.vlseg4eff.v v6, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv8i16.nxv8i16(
    <vscale x 8 x i16> %1, <vscale x 8 x i16> %1, <vscale x 8 x i16> %1, <vscale x 8 x i16> %1,
    <vscale x 8 x i16>* %0,
    <vscale x 8 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, iXLen } %a, 4
  store iXLen %c, iXLen* %4
  ret <vscale x 8 x i16> %b
}

declare { <vscale x 16 x i16>, <vscale x 16 x i16>, iXLen } @llvm.riscv.th.vlseg2eff.nxv16i16.nxv16i16(
  <vscale x 16 x i16>, <vscale x 16 x i16>,
  <vscale x 16 x i16>*,
  iXLen);

define <vscale x 16 x i16> @intrinsic_vlseg2eff_v_nxv16i16_nxv16i16(<vscale x 16 x i16>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv16i16_nxv16i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m4, d1
; RV32-NEXT:    th.vlseg2eff.v v4, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv16i16_nxv16i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m4, d1
; RV64-NEXT:    th.vlseg2eff.v v4, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 16 x i16>, <vscale x 16 x i16>, iXLen } @llvm.riscv.th.vlseg2eff.nxv16i16.nxv16i16(
    <vscale x 16 x i16> undef, <vscale x 16 x i16> undef,
    <vscale x 16 x i16>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 16 x i16>, <vscale x 16 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 16 x i16>, <vscale x 16 x i16>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 16 x i16> %b
}

declare { <vscale x 16 x i16>, <vscale x 16 x i16>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv16i16.nxv16i16(
  <vscale x 16 x i16>, <vscale x 16 x i16>,
  <vscale x 16 x i16>*,
  <vscale x 16 x i1>,
  iXLen);

define <vscale x 16 x i16> @intrinsic_vlseg2eff_mask_v_nxv16i16_nxv16i16(<vscale x 16 x i16>* %0, <vscale x 16 x i16> %1, <vscale x 16 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv16i16_nxv16i16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v4, v8
; RV32-NEXT:    th.vmv.v.v v5, v9
; RV32-NEXT:    th.vmv.v.v v6, v10
; RV32-NEXT:    th.vmv.v.v v7, v11
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m4, d1
; RV32-NEXT:    th.vlseg2eff.v v4, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv16i16_nxv16i16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v4, v8
; RV64-NEXT:    th.vmv.v.v v5, v9
; RV64-NEXT:    th.vmv.v.v v6, v10
; RV64-NEXT:    th.vmv.v.v v7, v11
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m4, d1
; RV64-NEXT:    th.vlseg2eff.v v4, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 16 x i16>, <vscale x 16 x i16>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv16i16.nxv16i16(
    <vscale x 16 x i16> %1, <vscale x 16 x i16> %1,
    <vscale x 16 x i16>* %0,
    <vscale x 16 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 16 x i16>, <vscale x 16 x i16>, iXLen } %a, 1
  %c = extractvalue { <vscale x 16 x i16>, <vscale x 16 x i16>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 16 x i16> %b
}

declare { <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg2eff.nxv4f16.nxv4f16(
  <vscale x 4 x half>, <vscale x 4 x half>,
  <vscale x 4 x half>*,
  iXLen);

define <vscale x 4 x half> @intrinsic_vlseg2eff_v_nxv4f16_nxv4f16(<vscale x 4 x half>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv4f16_nxv4f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg2eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv4f16_nxv4f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg2eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg2eff.nxv4f16.nxv4f16(
    <vscale x 4 x half> undef, <vscale x 4 x half> undef,
    <vscale x 4 x half>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x half> %b
}

declare { <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv4f16.nxv4f16(
  <vscale x 4 x half>, <vscale x 4 x half>,
  <vscale x 4 x half>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x half> @intrinsic_vlseg2eff_mask_v_nxv4f16_nxv4f16( <vscale x 4 x half>* %0, <vscale x 4 x half> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv4f16_nxv4f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg2eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv4f16_nxv4f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg2eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv4f16.nxv4f16(
    <vscale x 4 x half> %1, <vscale x 4 x half> %1,
    <vscale x 4 x half>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x half> %b
}

declare { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg3eff.nxv4f16.nxv4f16(
  <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>,
  <vscale x 4 x half>*,
  iXLen);

define <vscale x 4 x half> @intrinsic_vlseg3eff_v_nxv4f16_nxv4f16(<vscale x 4 x half>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_v_nxv4f16_nxv4f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg3eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_v_nxv4f16_nxv4f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg3eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg3eff.nxv4f16.nxv4f16(
    <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef,
    <vscale x 4 x half>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 3
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x half> %b
}

declare { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv4f16.nxv4f16(
  <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>,
  <vscale x 4 x half>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x half> @intrinsic_vlseg3eff_mask_v_nxv4f16_nxv4f16( <vscale x 4 x half>* %0, <vscale x 4 x half> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_mask_v_nxv4f16_nxv4f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg3eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_mask_v_nxv4f16_nxv4f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg3eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv4f16.nxv4f16(
    <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1,
    <vscale x 4 x half>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 3
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x half> %b
}

declare { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg4eff.nxv4f16.nxv4f16(
  <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>,
  <vscale x 4 x half>*,
  iXLen);

define <vscale x 4 x half> @intrinsic_vlseg4eff_v_nxv4f16_nxv4f16(<vscale x 4 x half>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_v_nxv4f16_nxv4f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg4eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_v_nxv4f16_nxv4f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg4eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg4eff.nxv4f16.nxv4f16(
    <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef,
    <vscale x 4 x half>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 4
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x half> %b
}

declare { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv4f16.nxv4f16(
  <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>,
  <vscale x 4 x half>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x half> @intrinsic_vlseg4eff_mask_v_nxv4f16_nxv4f16( <vscale x 4 x half>* %0, <vscale x 4 x half> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_mask_v_nxv4f16_nxv4f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg4eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_mask_v_nxv4f16_nxv4f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg4eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv4f16.nxv4f16(
    <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1,
    <vscale x 4 x half>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 4
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x half> %b
}

declare { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg5eff.nxv4f16.nxv4f16(
  <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>,
  <vscale x 4 x half>*,
  iXLen);

define <vscale x 4 x half> @intrinsic_vlseg5eff_v_nxv4f16_nxv4f16(<vscale x 4 x half>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg5eff_v_nxv4f16_nxv4f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg5eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg5eff_v_nxv4f16_nxv4f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg5eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg5eff.nxv4f16.nxv4f16(
    <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef,
    <vscale x 4 x half>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 5
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x half> %b
}

declare { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg5eff.mask.nxv4f16.nxv4f16(
  <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>,
  <vscale x 4 x half>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x half> @intrinsic_vlseg5eff_mask_v_nxv4f16_nxv4f16( <vscale x 4 x half>* %0, <vscale x 4 x half> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg5eff_mask_v_nxv4f16_nxv4f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg5eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg5eff_mask_v_nxv4f16_nxv4f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg5eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg5eff.mask.nxv4f16.nxv4f16(
    <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1,
    <vscale x 4 x half>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 5
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x half> %b
}

declare { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg6eff.nxv4f16.nxv4f16(
  <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>,
  <vscale x 4 x half>*,
  iXLen);

define <vscale x 4 x half> @intrinsic_vlseg6eff_v_nxv4f16_nxv4f16(<vscale x 4 x half>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg6eff_v_nxv4f16_nxv4f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg6eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg6eff_v_nxv4f16_nxv4f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg6eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg6eff.nxv4f16.nxv4f16(
    <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef,
    <vscale x 4 x half>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 6
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x half> %b
}

declare { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg6eff.mask.nxv4f16.nxv4f16(
  <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>,
  <vscale x 4 x half>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x half> @intrinsic_vlseg6eff_mask_v_nxv4f16_nxv4f16( <vscale x 4 x half>* %0, <vscale x 4 x half> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg6eff_mask_v_nxv4f16_nxv4f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg6eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg6eff_mask_v_nxv4f16_nxv4f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg6eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg6eff.mask.nxv4f16.nxv4f16(
    <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1,
    <vscale x 4 x half>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 6
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x half> %b
}

declare { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg7eff.nxv4f16.nxv4f16(
  <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>,
  <vscale x 4 x half>*,
  iXLen);

define <vscale x 4 x half> @intrinsic_vlseg7eff_v_nxv4f16_nxv4f16(<vscale x 4 x half>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg7eff_v_nxv4f16_nxv4f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg7eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg7eff_v_nxv4f16_nxv4f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg7eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg7eff.nxv4f16.nxv4f16(
    <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef,
    <vscale x 4 x half>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 7
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x half> %b
}

declare { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg7eff.mask.nxv4f16.nxv4f16(
  <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>,
  <vscale x 4 x half>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x half> @intrinsic_vlseg7eff_mask_v_nxv4f16_nxv4f16( <vscale x 4 x half>* %0, <vscale x 4 x half> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg7eff_mask_v_nxv4f16_nxv4f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v8
; RV32-NEXT:    th.vmv.v.v v14, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg7eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg7eff_mask_v_nxv4f16_nxv4f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v8
; RV64-NEXT:    th.vmv.v.v v14, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg7eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg7eff.mask.nxv4f16.nxv4f16(
    <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1,
    <vscale x 4 x half>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 7
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x half> %b
}

declare { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg8eff.nxv4f16.nxv4f16(
  <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>,
  <vscale x 4 x half>*,
  iXLen);

define <vscale x 4 x half> @intrinsic_vlseg8eff_v_nxv4f16_nxv4f16(<vscale x 4 x half>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg8eff_v_nxv4f16_nxv4f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg8eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg8eff_v_nxv4f16_nxv4f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg8eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg8eff.nxv4f16.nxv4f16(
    <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef, <vscale x 4 x half> undef,
    <vscale x 4 x half>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 8
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x half> %b
}

declare { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg8eff.mask.nxv4f16.nxv4f16(
  <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>,
  <vscale x 4 x half>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x half> @intrinsic_vlseg8eff_mask_v_nxv4f16_nxv4f16( <vscale x 4 x half>* %0, <vscale x 4 x half> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg8eff_mask_v_nxv4f16_nxv4f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v8
; RV32-NEXT:    th.vmv.v.v v14, v8
; RV32-NEXT:    th.vmv.v.v v15, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV32-NEXT:    th.vlseg8eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg8eff_mask_v_nxv4f16_nxv4f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v8
; RV64-NEXT:    th.vmv.v.v v14, v8
; RV64-NEXT:    th.vmv.v.v v15, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m1, d1
; RV64-NEXT:    th.vlseg8eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } @llvm.riscv.th.vlseg8eff.mask.nxv4f16.nxv4f16(
    <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1, <vscale x 4 x half> %1,
    <vscale x 4 x half>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, <vscale x 4 x half>, iXLen } %a, 8
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x half> %b
}

declare { <vscale x 8 x half>, <vscale x 8 x half>, iXLen } @llvm.riscv.th.vlseg2eff.nxv8f16.nxv8f16(
  <vscale x 8 x half>, <vscale x 8 x half>,
  <vscale x 8 x half>*,
  iXLen);

define <vscale x 8 x half> @intrinsic_vlseg2eff_v_nxv8f16_nxv8f16(<vscale x 8 x half>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv8f16_nxv8f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV32-NEXT:    th.vlseg2eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv8f16_nxv8f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV64-NEXT:    th.vlseg2eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x half>, <vscale x 8 x half>, iXLen } @llvm.riscv.th.vlseg2eff.nxv8f16.nxv8f16(
    <vscale x 8 x half> undef, <vscale x 8 x half> undef,
    <vscale x 8 x half>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 8 x half>, <vscale x 8 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 8 x half>, <vscale x 8 x half>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 8 x half> %b
}

declare { <vscale x 8 x half>, <vscale x 8 x half>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv8f16.nxv8f16(
  <vscale x 8 x half>, <vscale x 8 x half>,
  <vscale x 8 x half>*,
  <vscale x 8 x i1>,
  iXLen);

define <vscale x 8 x half> @intrinsic_vlseg2eff_mask_v_nxv8f16_nxv8f16( <vscale x 8 x half>* %0, <vscale x 8 x half> %1, <vscale x 8 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv8f16_nxv8f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV32-NEXT:    th.vlseg2eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv8f16_nxv8f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV64-NEXT:    th.vlseg2eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x half>, <vscale x 8 x half>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv8f16.nxv8f16(
    <vscale x 8 x half> %1, <vscale x 8 x half> %1,
    <vscale x 8 x half>* %0,
    <vscale x 8 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 8 x half>, <vscale x 8 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 8 x half>, <vscale x 8 x half>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 8 x half> %b
}

declare { <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, iXLen } @llvm.riscv.th.vlseg3eff.nxv8f16.nxv8f16(
  <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>,
  <vscale x 8 x half>*,
  iXLen);

define <vscale x 8 x half> @intrinsic_vlseg3eff_v_nxv8f16_nxv8f16(<vscale x 8 x half>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_v_nxv8f16_nxv8f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV32-NEXT:    th.vlseg3eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_v_nxv8f16_nxv8f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV64-NEXT:    th.vlseg3eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, iXLen } @llvm.riscv.th.vlseg3eff.nxv8f16.nxv8f16(
    <vscale x 8 x half> undef, <vscale x 8 x half> undef, <vscale x 8 x half> undef,
    <vscale x 8 x half>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, iXLen } %a, 3
  store iXLen %c, iXLen* %2
  ret <vscale x 8 x half> %b
}

declare { <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv8f16.nxv8f16(
  <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>,
  <vscale x 8 x half>*,
  <vscale x 8 x i1>,
  iXLen);

define <vscale x 8 x half> @intrinsic_vlseg3eff_mask_v_nxv8f16_nxv8f16( <vscale x 8 x half>* %0, <vscale x 8 x half> %1, <vscale x 8 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_mask_v_nxv8f16_nxv8f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v9
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV32-NEXT:    th.vlseg3eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_mask_v_nxv8f16_nxv8f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v9
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV64-NEXT:    th.vlseg3eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv8f16.nxv8f16(
    <vscale x 8 x half> %1, <vscale x 8 x half> %1, <vscale x 8 x half> %1,
    <vscale x 8 x half>* %0,
    <vscale x 8 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, iXLen } %a, 3
  store iXLen %c, iXLen* %4
  ret <vscale x 8 x half> %b
}

declare { <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, iXLen } @llvm.riscv.th.vlseg4eff.nxv8f16.nxv8f16(
  <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>,
  <vscale x 8 x half>*,
  iXLen);

define <vscale x 8 x half> @intrinsic_vlseg4eff_v_nxv8f16_nxv8f16(<vscale x 8 x half>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_v_nxv8f16_nxv8f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV32-NEXT:    th.vlseg4eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_v_nxv8f16_nxv8f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV64-NEXT:    th.vlseg4eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, iXLen } @llvm.riscv.th.vlseg4eff.nxv8f16.nxv8f16(
    <vscale x 8 x half> undef, <vscale x 8 x half> undef, <vscale x 8 x half> undef, <vscale x 8 x half> undef,
    <vscale x 8 x half>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, iXLen } %a, 4
  store iXLen %c, iXLen* %2
  ret <vscale x 8 x half> %b
}

declare { <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv8f16.nxv8f16(
  <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>,
  <vscale x 8 x half>*,
  <vscale x 8 x i1>,
  iXLen);

define <vscale x 8 x half> @intrinsic_vlseg4eff_mask_v_nxv8f16_nxv8f16( <vscale x 8 x half>* %0, <vscale x 8 x half> %1, <vscale x 8 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_mask_v_nxv8f16_nxv8f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v9
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v9
; RV32-NEXT:    th.vmv.v.v v14, v8
; RV32-NEXT:    th.vmv.v.v v15, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV32-NEXT:    th.vlseg4eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_mask_v_nxv8f16_nxv8f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v9
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v9
; RV64-NEXT:    th.vmv.v.v v14, v8
; RV64-NEXT:    th.vmv.v.v v15, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m2, d1
; RV64-NEXT:    th.vlseg4eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv8f16.nxv8f16(
    <vscale x 8 x half> %1, <vscale x 8 x half> %1, <vscale x 8 x half> %1, <vscale x 8 x half> %1,
    <vscale x 8 x half>* %0,
    <vscale x 8 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, <vscale x 8 x half>, iXLen } %a, 4
  store iXLen %c, iXLen* %4
  ret <vscale x 8 x half> %b
}

declare { <vscale x 16 x half>, <vscale x 16 x half>, iXLen } @llvm.riscv.th.vlseg2eff.nxv16f16.nxv16f16(
  <vscale x 16 x half>, <vscale x 16 x half>,
  <vscale x 16 x half>*,
  iXLen);

define <vscale x 16 x half> @intrinsic_vlseg2eff_v_nxv16f16_nxv16f16(<vscale x 16 x half>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv16f16_nxv16f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e16, m4, d1
; RV32-NEXT:    th.vlseg2eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv16f16_nxv16f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e16, m4, d1
; RV64-NEXT:    th.vlseg2eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 16 x half>, <vscale x 16 x half>, iXLen } @llvm.riscv.th.vlseg2eff.nxv16f16.nxv16f16(
    <vscale x 16 x half> undef, <vscale x 16 x half> undef,
    <vscale x 16 x half>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 16 x half>, <vscale x 16 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 16 x half>, <vscale x 16 x half>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 16 x half> %b
}

declare { <vscale x 16 x half>, <vscale x 16 x half>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv16f16.nxv16f16(
  <vscale x 16 x half>, <vscale x 16 x half>,
  <vscale x 16 x half>*,
  <vscale x 16 x i1>,
  iXLen);

define <vscale x 16 x half> @intrinsic_vlseg2eff_mask_v_nxv16f16_nxv16f16( <vscale x 16 x half>* %0, <vscale x 16 x half> %1, <vscale x 16 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv16f16_nxv16f16:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v9
; RV32-NEXT:    th.vmv.v.v v14, v10
; RV32-NEXT:    th.vmv.v.v v15, v11
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e16, m4, d1
; RV32-NEXT:    th.vlseg2eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv16f16_nxv16f16:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v9
; RV64-NEXT:    th.vmv.v.v v14, v10
; RV64-NEXT:    th.vmv.v.v v15, v11
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e16, m4, d1
; RV64-NEXT:    th.vlseg2eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 16 x half>, <vscale x 16 x half>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv16f16.nxv16f16(
    <vscale x 16 x half> %1, <vscale x 16 x half> %1,
    <vscale x 16 x half>* %0,
    <vscale x 16 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 16 x half>, <vscale x 16 x half>, iXLen } %a, 0
  %c = extractvalue { <vscale x 16 x half>, <vscale x 16 x half>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 16 x half> %b
}

declare { <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg2eff.nxv2i32.nxv2i32(
  <vscale x 2 x i32>, <vscale x 2 x i32>,
  <vscale x 2 x i32>*,
  iXLen);

define <vscale x 2 x i32> @intrinsic_vlseg2eff_v_nxv2i32_nxv2i32(<vscale x 2 x i32>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv2i32_nxv2i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg2eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv2i32_nxv2i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg2eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg2eff.nxv2i32.nxv2i32(
    <vscale x 2 x i32> undef, <vscale x 2 x i32> undef,
    <vscale x 2 x i32>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 2 x i32> %b
}

declare { <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv2i32.nxv2i32(
  <vscale x 2 x i32>, <vscale x 2 x i32>,
  <vscale x 2 x i32>*,
  <vscale x 2 x i1>,
  iXLen);

define <vscale x 2 x i32> @intrinsic_vlseg2eff_mask_v_nxv2i32_nxv2i32(<vscale x 2 x i32>* %0, <vscale x 2 x i32> %1, <vscale x 2 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv2i32_nxv2i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg2eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv2i32_nxv2i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg2eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv2i32.nxv2i32(
    <vscale x 2 x i32> %1, <vscale x 2 x i32> %1,
    <vscale x 2 x i32>* %0,
    <vscale x 2 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 2 x i32> %b
}

declare { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg3eff.nxv2i32.nxv2i32(
  <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>,
  <vscale x 2 x i32>*,
  iXLen);

define <vscale x 2 x i32> @intrinsic_vlseg3eff_v_nxv2i32_nxv2i32(<vscale x 2 x i32>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_v_nxv2i32_nxv2i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg3eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_v_nxv2i32_nxv2i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg3eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg3eff.nxv2i32.nxv2i32(
    <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef,
    <vscale x 2 x i32>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 3
  store iXLen %c, iXLen* %2
  ret <vscale x 2 x i32> %b
}

declare { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv2i32.nxv2i32(
  <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>,
  <vscale x 2 x i32>*,
  <vscale x 2 x i1>,
  iXLen);

define <vscale x 2 x i32> @intrinsic_vlseg3eff_mask_v_nxv2i32_nxv2i32(<vscale x 2 x i32>* %0, <vscale x 2 x i32> %1, <vscale x 2 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_mask_v_nxv2i32_nxv2i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg3eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_mask_v_nxv2i32_nxv2i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg3eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv2i32.nxv2i32(
    <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1,
    <vscale x 2 x i32>* %0,
    <vscale x 2 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 3
  store iXLen %c, iXLen* %4
  ret <vscale x 2 x i32> %b
}

declare { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg4eff.nxv2i32.nxv2i32(
  <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>,
  <vscale x 2 x i32>*,
  iXLen);

define <vscale x 2 x i32> @intrinsic_vlseg4eff_v_nxv2i32_nxv2i32(<vscale x 2 x i32>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_v_nxv2i32_nxv2i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg4eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_v_nxv2i32_nxv2i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg4eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg4eff.nxv2i32.nxv2i32(
    <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef,
    <vscale x 2 x i32>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 4
  store iXLen %c, iXLen* %2
  ret <vscale x 2 x i32> %b
}

declare { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv2i32.nxv2i32(
  <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>,
  <vscale x 2 x i32>*,
  <vscale x 2 x i1>,
  iXLen);

define <vscale x 2 x i32> @intrinsic_vlseg4eff_mask_v_nxv2i32_nxv2i32(<vscale x 2 x i32>* %0, <vscale x 2 x i32> %1, <vscale x 2 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_mask_v_nxv2i32_nxv2i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg4eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_mask_v_nxv2i32_nxv2i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg4eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv2i32.nxv2i32(
    <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1,
    <vscale x 2 x i32>* %0,
    <vscale x 2 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 4
  store iXLen %c, iXLen* %4
  ret <vscale x 2 x i32> %b
}

declare { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg5eff.nxv2i32.nxv2i32(
  <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>,
  <vscale x 2 x i32>*,
  iXLen);

define <vscale x 2 x i32> @intrinsic_vlseg5eff_v_nxv2i32_nxv2i32(<vscale x 2 x i32>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg5eff_v_nxv2i32_nxv2i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg5eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg5eff_v_nxv2i32_nxv2i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg5eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg5eff.nxv2i32.nxv2i32(
    <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef,
    <vscale x 2 x i32>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 5
  store iXLen %c, iXLen* %2
  ret <vscale x 2 x i32> %b
}

declare { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg5eff.mask.nxv2i32.nxv2i32(
  <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>,
  <vscale x 2 x i32>*,
  <vscale x 2 x i1>,
  iXLen);

define <vscale x 2 x i32> @intrinsic_vlseg5eff_mask_v_nxv2i32_nxv2i32(<vscale x 2 x i32>* %0, <vscale x 2 x i32> %1, <vscale x 2 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg5eff_mask_v_nxv2i32_nxv2i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg5eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg5eff_mask_v_nxv2i32_nxv2i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg5eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg5eff.mask.nxv2i32.nxv2i32(
    <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1,
    <vscale x 2 x i32>* %0,
    <vscale x 2 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 5
  store iXLen %c, iXLen* %4
  ret <vscale x 2 x i32> %b
}

declare { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg6eff.nxv2i32.nxv2i32(
  <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>,
  <vscale x 2 x i32>*,
  iXLen);

define <vscale x 2 x i32> @intrinsic_vlseg6eff_v_nxv2i32_nxv2i32(<vscale x 2 x i32>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg6eff_v_nxv2i32_nxv2i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg6eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg6eff_v_nxv2i32_nxv2i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg6eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg6eff.nxv2i32.nxv2i32(
    <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef,
    <vscale x 2 x i32>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 6
  store iXLen %c, iXLen* %2
  ret <vscale x 2 x i32> %b
}

declare { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg6eff.mask.nxv2i32.nxv2i32(
  <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>,
  <vscale x 2 x i32>*,
  <vscale x 2 x i1>,
  iXLen);

define <vscale x 2 x i32> @intrinsic_vlseg6eff_mask_v_nxv2i32_nxv2i32(<vscale x 2 x i32>* %0, <vscale x 2 x i32> %1, <vscale x 2 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg6eff_mask_v_nxv2i32_nxv2i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg6eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg6eff_mask_v_nxv2i32_nxv2i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg6eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg6eff.mask.nxv2i32.nxv2i32(
    <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1,
    <vscale x 2 x i32>* %0,
    <vscale x 2 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 6
  store iXLen %c, iXLen* %4
  ret <vscale x 2 x i32> %b
}

declare { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg7eff.nxv2i32.nxv2i32(
  <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>,
  <vscale x 2 x i32>*,
  iXLen);

define <vscale x 2 x i32> @intrinsic_vlseg7eff_v_nxv2i32_nxv2i32(<vscale x 2 x i32>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg7eff_v_nxv2i32_nxv2i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg7eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg7eff_v_nxv2i32_nxv2i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg7eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg7eff.nxv2i32.nxv2i32(
    <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef,
    <vscale x 2 x i32>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 7
  store iXLen %c, iXLen* %2
  ret <vscale x 2 x i32> %b
}

declare { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg7eff.mask.nxv2i32.nxv2i32(
  <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>,
  <vscale x 2 x i32>*,
  <vscale x 2 x i1>,
  iXLen);

define <vscale x 2 x i32> @intrinsic_vlseg7eff_mask_v_nxv2i32_nxv2i32(<vscale x 2 x i32>* %0, <vscale x 2 x i32> %1, <vscale x 2 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg7eff_mask_v_nxv2i32_nxv2i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg7eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg7eff_mask_v_nxv2i32_nxv2i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg7eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg7eff.mask.nxv2i32.nxv2i32(
    <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1,
    <vscale x 2 x i32>* %0,
    <vscale x 2 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 7
  store iXLen %c, iXLen* %4
  ret <vscale x 2 x i32> %b
}

declare { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg8eff.nxv2i32.nxv2i32(
  <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>,
  <vscale x 2 x i32>*,
  iXLen);

define <vscale x 2 x i32> @intrinsic_vlseg8eff_v_nxv2i32_nxv2i32(<vscale x 2 x i32>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg8eff_v_nxv2i32_nxv2i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg8eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg8eff_v_nxv2i32_nxv2i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg8eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg8eff.nxv2i32.nxv2i32(
    <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef, <vscale x 2 x i32> undef,
    <vscale x 2 x i32>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 8
  store iXLen %c, iXLen* %2
  ret <vscale x 2 x i32> %b
}

declare { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg8eff.mask.nxv2i32.nxv2i32(
  <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>,
  <vscale x 2 x i32>*,
  <vscale x 2 x i1>,
  iXLen);

define <vscale x 2 x i32> @intrinsic_vlseg8eff_mask_v_nxv2i32_nxv2i32(<vscale x 2 x i32>* %0, <vscale x 2 x i32> %1, <vscale x 2 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg8eff_mask_v_nxv2i32_nxv2i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v8
; RV32-NEXT:    th.vmv.v.v v14, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg8eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg8eff_mask_v_nxv2i32_nxv2i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v8
; RV64-NEXT:    th.vmv.v.v v14, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg8eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } @llvm.riscv.th.vlseg8eff.mask.nxv2i32.nxv2i32(
    <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1, <vscale x 2 x i32> %1,
    <vscale x 2 x i32>* %0,
    <vscale x 2 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, <vscale x 2 x i32>, iXLen } %a, 8
  store iXLen %c, iXLen* %4
  ret <vscale x 2 x i32> %b
}

declare { <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } @llvm.riscv.th.vlseg2eff.nxv4i32.nxv4i32(
  <vscale x 4 x i32>, <vscale x 4 x i32>,
  <vscale x 4 x i32>*,
  iXLen);

define <vscale x 4 x i32> @intrinsic_vlseg2eff_v_nxv4i32_nxv4i32(<vscale x 4 x i32>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv4i32_nxv4i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV32-NEXT:    th.vlseg2eff.v v6, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv4i32_nxv4i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV64-NEXT:    th.vlseg2eff.v v6, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } @llvm.riscv.th.vlseg2eff.nxv4i32.nxv4i32(
    <vscale x 4 x i32> undef, <vscale x 4 x i32> undef,
    <vscale x 4 x i32>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x i32> %b
}

declare { <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv4i32.nxv4i32(
  <vscale x 4 x i32>, <vscale x 4 x i32>,
  <vscale x 4 x i32>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x i32> @intrinsic_vlseg2eff_mask_v_nxv4i32_nxv4i32(<vscale x 4 x i32>* %0, <vscale x 4 x i32> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv4i32_nxv4i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v6, v8
; RV32-NEXT:    th.vmv.v.v v7, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV32-NEXT:    th.vlseg2eff.v v6, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv4i32_nxv4i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v6, v8
; RV64-NEXT:    th.vmv.v.v v7, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV64-NEXT:    th.vlseg2eff.v v6, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv4i32.nxv4i32(
    <vscale x 4 x i32> %1, <vscale x 4 x i32> %1,
    <vscale x 4 x i32>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x i32> %b
}

declare { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } @llvm.riscv.th.vlseg3eff.nxv4i32.nxv4i32(
  <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>,
  <vscale x 4 x i32>*,
  iXLen);

define <vscale x 4 x i32> @intrinsic_vlseg3eff_v_nxv4i32_nxv4i32(<vscale x 4 x i32>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_v_nxv4i32_nxv4i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV32-NEXT:    th.vlseg3eff.v v6, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_v_nxv4i32_nxv4i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV64-NEXT:    th.vlseg3eff.v v6, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } @llvm.riscv.th.vlseg3eff.nxv4i32.nxv4i32(
    <vscale x 4 x i32> undef, <vscale x 4 x i32> undef, <vscale x 4 x i32> undef,
    <vscale x 4 x i32>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } %a, 3
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x i32> %b
}

declare { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv4i32.nxv4i32(
  <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>,
  <vscale x 4 x i32>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x i32> @intrinsic_vlseg3eff_mask_v_nxv4i32_nxv4i32(<vscale x 4 x i32>* %0, <vscale x 4 x i32> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_mask_v_nxv4i32_nxv4i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v6, v8
; RV32-NEXT:    th.vmv.v.v v7, v9
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV32-NEXT:    th.vlseg3eff.v v6, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_mask_v_nxv4i32_nxv4i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v6, v8
; RV64-NEXT:    th.vmv.v.v v7, v9
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV64-NEXT:    th.vlseg3eff.v v6, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv4i32.nxv4i32(
    <vscale x 4 x i32> %1, <vscale x 4 x i32> %1, <vscale x 4 x i32> %1,
    <vscale x 4 x i32>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } %a, 3
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x i32> %b
}

declare { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } @llvm.riscv.th.vlseg4eff.nxv4i32.nxv4i32(
  <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>,
  <vscale x 4 x i32>*,
  iXLen);

define <vscale x 4 x i32> @intrinsic_vlseg4eff_v_nxv4i32_nxv4i32(<vscale x 4 x i32>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_v_nxv4i32_nxv4i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV32-NEXT:    th.vlseg4eff.v v6, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_v_nxv4i32_nxv4i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV64-NEXT:    th.vlseg4eff.v v6, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } @llvm.riscv.th.vlseg4eff.nxv4i32.nxv4i32(
    <vscale x 4 x i32> undef, <vscale x 4 x i32> undef, <vscale x 4 x i32> undef, <vscale x 4 x i32> undef,
    <vscale x 4 x i32>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } %a, 4
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x i32> %b
}

declare { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv4i32.nxv4i32(
  <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>,
  <vscale x 4 x i32>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x i32> @intrinsic_vlseg4eff_mask_v_nxv4i32_nxv4i32(<vscale x 4 x i32>* %0, <vscale x 4 x i32> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_mask_v_nxv4i32_nxv4i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v6, v8
; RV32-NEXT:    th.vmv.v.v v7, v9
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v9
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV32-NEXT:    th.vlseg4eff.v v6, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_mask_v_nxv4i32_nxv4i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v6, v8
; RV64-NEXT:    th.vmv.v.v v7, v9
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v9
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV64-NEXT:    th.vlseg4eff.v v6, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv4i32.nxv4i32(
    <vscale x 4 x i32> %1, <vscale x 4 x i32> %1, <vscale x 4 x i32> %1, <vscale x 4 x i32> %1,
    <vscale x 4 x i32>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, <vscale x 4 x i32>, iXLen } %a, 4
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x i32> %b
}

declare { <vscale x 8 x i32>, <vscale x 8 x i32>, iXLen } @llvm.riscv.th.vlseg2eff.nxv8i32.nxv8i32(
  <vscale x 8 x i32>, <vscale x 8 x i32>,
  <vscale x 8 x i32>*,
  iXLen);

define <vscale x 8 x i32> @intrinsic_vlseg2eff_v_nxv8i32_nxv8i32(<vscale x 8 x i32>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv8i32_nxv8i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m4, d1
; RV32-NEXT:    th.vlseg2eff.v v4, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv8i32_nxv8i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m4, d1
; RV64-NEXT:    th.vlseg2eff.v v4, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i32>, <vscale x 8 x i32>, iXLen } @llvm.riscv.th.vlseg2eff.nxv8i32.nxv8i32(
    <vscale x 8 x i32> undef, <vscale x 8 x i32> undef,
    <vscale x 8 x i32>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 8 x i32>, <vscale x 8 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i32>, <vscale x 8 x i32>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 8 x i32> %b
}

declare { <vscale x 8 x i32>, <vscale x 8 x i32>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv8i32.nxv8i32(
  <vscale x 8 x i32>, <vscale x 8 x i32>,
  <vscale x 8 x i32>*,
  <vscale x 8 x i1>,
  iXLen);

define <vscale x 8 x i32> @intrinsic_vlseg2eff_mask_v_nxv8i32_nxv8i32(<vscale x 8 x i32>* %0, <vscale x 8 x i32> %1, <vscale x 8 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv8i32_nxv8i32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v4, v8
; RV32-NEXT:    th.vmv.v.v v5, v9
; RV32-NEXT:    th.vmv.v.v v6, v10
; RV32-NEXT:    th.vmv.v.v v7, v11
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m4, d1
; RV32-NEXT:    th.vlseg2eff.v v4, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv8i32_nxv8i32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v4, v8
; RV64-NEXT:    th.vmv.v.v v5, v9
; RV64-NEXT:    th.vmv.v.v v6, v10
; RV64-NEXT:    th.vmv.v.v v7, v11
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m4, d1
; RV64-NEXT:    th.vlseg2eff.v v4, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x i32>, <vscale x 8 x i32>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv8i32.nxv8i32(
    <vscale x 8 x i32> %1, <vscale x 8 x i32> %1,
    <vscale x 8 x i32>* %0,
    <vscale x 8 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 8 x i32>, <vscale x 8 x i32>, iXLen } %a, 1
  %c = extractvalue { <vscale x 8 x i32>, <vscale x 8 x i32>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 8 x i32> %b
}

declare { <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg2eff.nxv2f32.nxv2f32(
  <vscale x 2 x float>, <vscale x 2 x float>,
  <vscale x 2 x float>*,
  iXLen);

define <vscale x 2 x float> @intrinsic_vlseg2eff_v_nxv2f32_nxv2f32(<vscale x 2 x float>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv2f32_nxv2f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg2eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv2f32_nxv2f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg2eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg2eff.nxv2f32.nxv2f32(
    <vscale x 2 x float> undef, <vscale x 2 x float> undef,
    <vscale x 2 x float>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 2 x float> %b
}

declare { <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv2f32.nxv2f32(
  <vscale x 2 x float>, <vscale x 2 x float>,
  <vscale x 2 x float>*,
  <vscale x 2 x i1>,
  iXLen);

define <vscale x 2 x float> @intrinsic_vlseg2eff_mask_v_nxv2f32_nxv2f32( <vscale x 2 x float>* %0, <vscale x 2 x float> %1, <vscale x 2 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv2f32_nxv2f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg2eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv2f32_nxv2f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg2eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv2f32.nxv2f32(
    <vscale x 2 x float> %1, <vscale x 2 x float> %1,
    <vscale x 2 x float>* %0,
    <vscale x 2 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 2 x float> %b
}

declare { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg3eff.nxv2f32.nxv2f32(
  <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>,
  <vscale x 2 x float>*,
  iXLen);

define <vscale x 2 x float> @intrinsic_vlseg3eff_v_nxv2f32_nxv2f32(<vscale x 2 x float>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_v_nxv2f32_nxv2f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg3eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_v_nxv2f32_nxv2f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg3eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg3eff.nxv2f32.nxv2f32(
    <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef,
    <vscale x 2 x float>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 3
  store iXLen %c, iXLen* %2
  ret <vscale x 2 x float> %b
}

declare { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv2f32.nxv2f32(
  <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>,
  <vscale x 2 x float>*,
  <vscale x 2 x i1>,
  iXLen);

define <vscale x 2 x float> @intrinsic_vlseg3eff_mask_v_nxv2f32_nxv2f32( <vscale x 2 x float>* %0, <vscale x 2 x float> %1, <vscale x 2 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_mask_v_nxv2f32_nxv2f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg3eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_mask_v_nxv2f32_nxv2f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg3eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv2f32.nxv2f32(
    <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1,
    <vscale x 2 x float>* %0,
    <vscale x 2 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 3
  store iXLen %c, iXLen* %4
  ret <vscale x 2 x float> %b
}

declare { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg4eff.nxv2f32.nxv2f32(
  <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>,
  <vscale x 2 x float>*,
  iXLen);

define <vscale x 2 x float> @intrinsic_vlseg4eff_v_nxv2f32_nxv2f32(<vscale x 2 x float>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_v_nxv2f32_nxv2f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg4eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_v_nxv2f32_nxv2f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg4eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg4eff.nxv2f32.nxv2f32(
    <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef,
    <vscale x 2 x float>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 4
  store iXLen %c, iXLen* %2
  ret <vscale x 2 x float> %b
}

declare { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv2f32.nxv2f32(
  <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>,
  <vscale x 2 x float>*,
  <vscale x 2 x i1>,
  iXLen);

define <vscale x 2 x float> @intrinsic_vlseg4eff_mask_v_nxv2f32_nxv2f32( <vscale x 2 x float>* %0, <vscale x 2 x float> %1, <vscale x 2 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_mask_v_nxv2f32_nxv2f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg4eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_mask_v_nxv2f32_nxv2f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg4eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv2f32.nxv2f32(
    <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1,
    <vscale x 2 x float>* %0,
    <vscale x 2 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 4
  store iXLen %c, iXLen* %4
  ret <vscale x 2 x float> %b
}

declare { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg5eff.nxv2f32.nxv2f32(
  <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>,
  <vscale x 2 x float>*,
  iXLen);

define <vscale x 2 x float> @intrinsic_vlseg5eff_v_nxv2f32_nxv2f32(<vscale x 2 x float>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg5eff_v_nxv2f32_nxv2f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg5eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg5eff_v_nxv2f32_nxv2f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg5eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg5eff.nxv2f32.nxv2f32(
    <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef,
    <vscale x 2 x float>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 5
  store iXLen %c, iXLen* %2
  ret <vscale x 2 x float> %b
}

declare { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg5eff.mask.nxv2f32.nxv2f32(
  <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>,
  <vscale x 2 x float>*,
  <vscale x 2 x i1>,
  iXLen);

define <vscale x 2 x float> @intrinsic_vlseg5eff_mask_v_nxv2f32_nxv2f32( <vscale x 2 x float>* %0, <vscale x 2 x float> %1, <vscale x 2 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg5eff_mask_v_nxv2f32_nxv2f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg5eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg5eff_mask_v_nxv2f32_nxv2f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg5eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg5eff.mask.nxv2f32.nxv2f32(
    <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1,
    <vscale x 2 x float>* %0,
    <vscale x 2 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 5
  store iXLen %c, iXLen* %4
  ret <vscale x 2 x float> %b
}

declare { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg6eff.nxv2f32.nxv2f32(
  <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>,
  <vscale x 2 x float>*,
  iXLen);

define <vscale x 2 x float> @intrinsic_vlseg6eff_v_nxv2f32_nxv2f32(<vscale x 2 x float>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg6eff_v_nxv2f32_nxv2f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg6eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg6eff_v_nxv2f32_nxv2f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg6eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg6eff.nxv2f32.nxv2f32(
    <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef,
    <vscale x 2 x float>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 6
  store iXLen %c, iXLen* %2
  ret <vscale x 2 x float> %b
}

declare { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg6eff.mask.nxv2f32.nxv2f32(
  <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>,
  <vscale x 2 x float>*,
  <vscale x 2 x i1>,
  iXLen);

define <vscale x 2 x float> @intrinsic_vlseg6eff_mask_v_nxv2f32_nxv2f32( <vscale x 2 x float>* %0, <vscale x 2 x float> %1, <vscale x 2 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg6eff_mask_v_nxv2f32_nxv2f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg6eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg6eff_mask_v_nxv2f32_nxv2f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg6eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg6eff.mask.nxv2f32.nxv2f32(
    <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1,
    <vscale x 2 x float>* %0,
    <vscale x 2 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 6
  store iXLen %c, iXLen* %4
  ret <vscale x 2 x float> %b
}

declare { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg7eff.nxv2f32.nxv2f32(
  <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>,
  <vscale x 2 x float>*,
  iXLen);

define <vscale x 2 x float> @intrinsic_vlseg7eff_v_nxv2f32_nxv2f32(<vscale x 2 x float>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg7eff_v_nxv2f32_nxv2f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg7eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg7eff_v_nxv2f32_nxv2f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg7eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg7eff.nxv2f32.nxv2f32(
    <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef,
    <vscale x 2 x float>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 7
  store iXLen %c, iXLen* %2
  ret <vscale x 2 x float> %b
}

declare { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg7eff.mask.nxv2f32.nxv2f32(
  <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>,
  <vscale x 2 x float>*,
  <vscale x 2 x i1>,
  iXLen);

define <vscale x 2 x float> @intrinsic_vlseg7eff_mask_v_nxv2f32_nxv2f32( <vscale x 2 x float>* %0, <vscale x 2 x float> %1, <vscale x 2 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg7eff_mask_v_nxv2f32_nxv2f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v8
; RV32-NEXT:    th.vmv.v.v v14, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg7eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg7eff_mask_v_nxv2f32_nxv2f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v8
; RV64-NEXT:    th.vmv.v.v v14, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg7eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg7eff.mask.nxv2f32.nxv2f32(
    <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1,
    <vscale x 2 x float>* %0,
    <vscale x 2 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 7
  store iXLen %c, iXLen* %4
  ret <vscale x 2 x float> %b
}

declare { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg8eff.nxv2f32.nxv2f32(
  <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>,
  <vscale x 2 x float>*,
  iXLen);

define <vscale x 2 x float> @intrinsic_vlseg8eff_v_nxv2f32_nxv2f32(<vscale x 2 x float>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg8eff_v_nxv2f32_nxv2f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg8eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg8eff_v_nxv2f32_nxv2f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg8eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg8eff.nxv2f32.nxv2f32(
    <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef, <vscale x 2 x float> undef,
    <vscale x 2 x float>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 8
  store iXLen %c, iXLen* %2
  ret <vscale x 2 x float> %b
}

declare { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg8eff.mask.nxv2f32.nxv2f32(
  <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>,
  <vscale x 2 x float>*,
  <vscale x 2 x i1>,
  iXLen);

define <vscale x 2 x float> @intrinsic_vlseg8eff_mask_v_nxv2f32_nxv2f32( <vscale x 2 x float>* %0, <vscale x 2 x float> %1, <vscale x 2 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg8eff_mask_v_nxv2f32_nxv2f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v8
; RV32-NEXT:    th.vmv.v.v v14, v8
; RV32-NEXT:    th.vmv.v.v v15, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV32-NEXT:    th.vlseg8eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg8eff_mask_v_nxv2f32_nxv2f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v8
; RV64-NEXT:    th.vmv.v.v v14, v8
; RV64-NEXT:    th.vmv.v.v v15, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m1, d1
; RV64-NEXT:    th.vlseg8eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } @llvm.riscv.th.vlseg8eff.mask.nxv2f32.nxv2f32(
    <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1, <vscale x 2 x float> %1,
    <vscale x 2 x float>* %0,
    <vscale x 2 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, <vscale x 2 x float>, iXLen } %a, 8
  store iXLen %c, iXLen* %4
  ret <vscale x 2 x float> %b
}

declare { <vscale x 4 x float>, <vscale x 4 x float>, iXLen } @llvm.riscv.th.vlseg2eff.nxv4f32.nxv4f32(
  <vscale x 4 x float>, <vscale x 4 x float>,
  <vscale x 4 x float>*,
  iXLen);

define <vscale x 4 x float> @intrinsic_vlseg2eff_v_nxv4f32_nxv4f32(<vscale x 4 x float>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv4f32_nxv4f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV32-NEXT:    th.vlseg2eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv4f32_nxv4f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV64-NEXT:    th.vlseg2eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x float>, <vscale x 4 x float>, iXLen } @llvm.riscv.th.vlseg2eff.nxv4f32.nxv4f32(
    <vscale x 4 x float> undef, <vscale x 4 x float> undef,
    <vscale x 4 x float>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x float>, <vscale x 4 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x float>, <vscale x 4 x float>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x float> %b
}

declare { <vscale x 4 x float>, <vscale x 4 x float>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv4f32.nxv4f32(
  <vscale x 4 x float>, <vscale x 4 x float>,
  <vscale x 4 x float>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x float> @intrinsic_vlseg2eff_mask_v_nxv4f32_nxv4f32( <vscale x 4 x float>* %0, <vscale x 4 x float> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv4f32_nxv4f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV32-NEXT:    th.vlseg2eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv4f32_nxv4f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV64-NEXT:    th.vlseg2eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x float>, <vscale x 4 x float>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv4f32.nxv4f32(
    <vscale x 4 x float> %1, <vscale x 4 x float> %1,
    <vscale x 4 x float>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x float>, <vscale x 4 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x float>, <vscale x 4 x float>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x float> %b
}

declare { <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen } @llvm.riscv.th.vlseg3eff.nxv4f32.nxv4f32(
  <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>,
  <vscale x 4 x float>*,
  iXLen);

define <vscale x 4 x float> @intrinsic_vlseg3eff_v_nxv4f32_nxv4f32(<vscale x 4 x float>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_v_nxv4f32_nxv4f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV32-NEXT:    th.vlseg3eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_v_nxv4f32_nxv4f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV64-NEXT:    th.vlseg3eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen } @llvm.riscv.th.vlseg3eff.nxv4f32.nxv4f32(
    <vscale x 4 x float> undef, <vscale x 4 x float> undef, <vscale x 4 x float> undef,
    <vscale x 4 x float>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen } %a, 3
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x float> %b
}

declare { <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv4f32.nxv4f32(
  <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>,
  <vscale x 4 x float>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x float> @intrinsic_vlseg3eff_mask_v_nxv4f32_nxv4f32( <vscale x 4 x float>* %0, <vscale x 4 x float> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_mask_v_nxv4f32_nxv4f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v9
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV32-NEXT:    th.vlseg3eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_mask_v_nxv4f32_nxv4f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v9
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV64-NEXT:    th.vlseg3eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv4f32.nxv4f32(
    <vscale x 4 x float> %1, <vscale x 4 x float> %1, <vscale x 4 x float> %1,
    <vscale x 4 x float>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen } %a, 3
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x float> %b
}

declare { <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen } @llvm.riscv.th.vlseg4eff.nxv4f32.nxv4f32(
  <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>,
  <vscale x 4 x float>*,
  iXLen);

define <vscale x 4 x float> @intrinsic_vlseg4eff_v_nxv4f32_nxv4f32(<vscale x 4 x float>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_v_nxv4f32_nxv4f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV32-NEXT:    th.vlseg4eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_v_nxv4f32_nxv4f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV64-NEXT:    th.vlseg4eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen } @llvm.riscv.th.vlseg4eff.nxv4f32.nxv4f32(
    <vscale x 4 x float> undef, <vscale x 4 x float> undef, <vscale x 4 x float> undef, <vscale x 4 x float> undef,
    <vscale x 4 x float>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen } %a, 4
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x float> %b
}

declare { <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv4f32.nxv4f32(
  <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>,
  <vscale x 4 x float>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x float> @intrinsic_vlseg4eff_mask_v_nxv4f32_nxv4f32( <vscale x 4 x float>* %0, <vscale x 4 x float> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_mask_v_nxv4f32_nxv4f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v9
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v9
; RV32-NEXT:    th.vmv.v.v v14, v8
; RV32-NEXT:    th.vmv.v.v v15, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV32-NEXT:    th.vlseg4eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_mask_v_nxv4f32_nxv4f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v9
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v9
; RV64-NEXT:    th.vmv.v.v v14, v8
; RV64-NEXT:    th.vmv.v.v v15, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m2, d1
; RV64-NEXT:    th.vlseg4eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv4f32.nxv4f32(
    <vscale x 4 x float> %1, <vscale x 4 x float> %1, <vscale x 4 x float> %1, <vscale x 4 x float> %1,
    <vscale x 4 x float>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, <vscale x 4 x float>, iXLen } %a, 4
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x float> %b
}

declare { <vscale x 8 x float>, <vscale x 8 x float>, iXLen } @llvm.riscv.th.vlseg2eff.nxv8f32.nxv8f32(
  <vscale x 8 x float>, <vscale x 8 x float>,
  <vscale x 8 x float>*,
  iXLen);

define <vscale x 8 x float> @intrinsic_vlseg2eff_v_nxv8f32_nxv8f32(<vscale x 8 x float>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv8f32_nxv8f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e32, m4, d1
; RV32-NEXT:    th.vlseg2eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv8f32_nxv8f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e32, m4, d1
; RV64-NEXT:    th.vlseg2eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x float>, <vscale x 8 x float>, iXLen } @llvm.riscv.th.vlseg2eff.nxv8f32.nxv8f32(
    <vscale x 8 x float> undef, <vscale x 8 x float> undef,
    <vscale x 8 x float>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 8 x float>, <vscale x 8 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 8 x float>, <vscale x 8 x float>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 8 x float> %b
}

declare { <vscale x 8 x float>, <vscale x 8 x float>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv8f32.nxv8f32(
  <vscale x 8 x float>, <vscale x 8 x float>,
  <vscale x 8 x float>*,
  <vscale x 8 x i1>,
  iXLen);

define <vscale x 8 x float> @intrinsic_vlseg2eff_mask_v_nxv8f32_nxv8f32( <vscale x 8 x float>* %0, <vscale x 8 x float> %1, <vscale x 8 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv8f32_nxv8f32:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v9
; RV32-NEXT:    th.vmv.v.v v14, v10
; RV32-NEXT:    th.vmv.v.v v15, v11
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e32, m4, d1
; RV32-NEXT:    th.vlseg2eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv8f32_nxv8f32:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v9
; RV64-NEXT:    th.vmv.v.v v14, v10
; RV64-NEXT:    th.vmv.v.v v15, v11
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e32, m4, d1
; RV64-NEXT:    th.vlseg2eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 8 x float>, <vscale x 8 x float>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv8f32.nxv8f32(
    <vscale x 8 x float> %1, <vscale x 8 x float> %1,
    <vscale x 8 x float>* %0,
    <vscale x 8 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 8 x float>, <vscale x 8 x float>, iXLen } %a, 0
  %c = extractvalue { <vscale x 8 x float>, <vscale x 8 x float>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 8 x float> %b
}

declare { <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg2eff.nxv1i64.nxv1i64(
  <vscale x 1 x i64>, <vscale x 1 x i64>,
  <vscale x 1 x i64>*,
  iXLen);

define <vscale x 1 x i64> @intrinsic_vlseg2eff_v_nxv1i64_nxv1i64(<vscale x 1 x i64>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv1i64_nxv1i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg2eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv1i64_nxv1i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg2eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg2eff.nxv1i64.nxv1i64(
    <vscale x 1 x i64> undef, <vscale x 1 x i64> undef,
    <vscale x 1 x i64>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 1 x i64> %b
}

declare { <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv1i64.nxv1i64(
  <vscale x 1 x i64>, <vscale x 1 x i64>,
  <vscale x 1 x i64>*,
  <vscale x 1 x i1>,
  iXLen);

define <vscale x 1 x i64> @intrinsic_vlseg2eff_mask_v_nxv1i64_nxv1i64(<vscale x 1 x i64>* %0, <vscale x 1 x i64> %1, <vscale x 1 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv1i64_nxv1i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg2eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv1i64_nxv1i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg2eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv1i64.nxv1i64(
    <vscale x 1 x i64> %1, <vscale x 1 x i64> %1,
    <vscale x 1 x i64>* %0,
    <vscale x 1 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 1 x i64> %b
}

declare { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg3eff.nxv1i64.nxv1i64(
  <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>,
  <vscale x 1 x i64>*,
  iXLen);

define <vscale x 1 x i64> @intrinsic_vlseg3eff_v_nxv1i64_nxv1i64(<vscale x 1 x i64>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_v_nxv1i64_nxv1i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg3eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_v_nxv1i64_nxv1i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg3eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg3eff.nxv1i64.nxv1i64(
    <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef,
    <vscale x 1 x i64>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 3
  store iXLen %c, iXLen* %2
  ret <vscale x 1 x i64> %b
}

declare { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv1i64.nxv1i64(
  <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>,
  <vscale x 1 x i64>*,
  <vscale x 1 x i1>,
  iXLen);

define <vscale x 1 x i64> @intrinsic_vlseg3eff_mask_v_nxv1i64_nxv1i64(<vscale x 1 x i64>* %0, <vscale x 1 x i64> %1, <vscale x 1 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_mask_v_nxv1i64_nxv1i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg3eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_mask_v_nxv1i64_nxv1i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg3eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv1i64.nxv1i64(
    <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1,
    <vscale x 1 x i64>* %0,
    <vscale x 1 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 3
  store iXLen %c, iXLen* %4
  ret <vscale x 1 x i64> %b
}

declare { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg4eff.nxv1i64.nxv1i64(
  <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>,
  <vscale x 1 x i64>*,
  iXLen);

define <vscale x 1 x i64> @intrinsic_vlseg4eff_v_nxv1i64_nxv1i64(<vscale x 1 x i64>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_v_nxv1i64_nxv1i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg4eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_v_nxv1i64_nxv1i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg4eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg4eff.nxv1i64.nxv1i64(
    <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef,
    <vscale x 1 x i64>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 4
  store iXLen %c, iXLen* %2
  ret <vscale x 1 x i64> %b
}

declare { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv1i64.nxv1i64(
  <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>,
  <vscale x 1 x i64>*,
  <vscale x 1 x i1>,
  iXLen);

define <vscale x 1 x i64> @intrinsic_vlseg4eff_mask_v_nxv1i64_nxv1i64(<vscale x 1 x i64>* %0, <vscale x 1 x i64> %1, <vscale x 1 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_mask_v_nxv1i64_nxv1i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg4eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_mask_v_nxv1i64_nxv1i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg4eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv1i64.nxv1i64(
    <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1,
    <vscale x 1 x i64>* %0,
    <vscale x 1 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 4
  store iXLen %c, iXLen* %4
  ret <vscale x 1 x i64> %b
}

declare { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg5eff.nxv1i64.nxv1i64(
  <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>,
  <vscale x 1 x i64>*,
  iXLen);

define <vscale x 1 x i64> @intrinsic_vlseg5eff_v_nxv1i64_nxv1i64(<vscale x 1 x i64>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg5eff_v_nxv1i64_nxv1i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg5eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg5eff_v_nxv1i64_nxv1i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg5eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg5eff.nxv1i64.nxv1i64(
    <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef,
    <vscale x 1 x i64>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 5
  store iXLen %c, iXLen* %2
  ret <vscale x 1 x i64> %b
}

declare { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg5eff.mask.nxv1i64.nxv1i64(
  <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>,
  <vscale x 1 x i64>*,
  <vscale x 1 x i1>,
  iXLen);

define <vscale x 1 x i64> @intrinsic_vlseg5eff_mask_v_nxv1i64_nxv1i64(<vscale x 1 x i64>* %0, <vscale x 1 x i64> %1, <vscale x 1 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg5eff_mask_v_nxv1i64_nxv1i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg5eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg5eff_mask_v_nxv1i64_nxv1i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg5eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg5eff.mask.nxv1i64.nxv1i64(
    <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1,
    <vscale x 1 x i64>* %0,
    <vscale x 1 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 5
  store iXLen %c, iXLen* %4
  ret <vscale x 1 x i64> %b
}

declare { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg6eff.nxv1i64.nxv1i64(
  <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>,
  <vscale x 1 x i64>*,
  iXLen);

define <vscale x 1 x i64> @intrinsic_vlseg6eff_v_nxv1i64_nxv1i64(<vscale x 1 x i64>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg6eff_v_nxv1i64_nxv1i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg6eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg6eff_v_nxv1i64_nxv1i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg6eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg6eff.nxv1i64.nxv1i64(
    <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef,
    <vscale x 1 x i64>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 6
  store iXLen %c, iXLen* %2
  ret <vscale x 1 x i64> %b
}

declare { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg6eff.mask.nxv1i64.nxv1i64(
  <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>,
  <vscale x 1 x i64>*,
  <vscale x 1 x i1>,
  iXLen);

define <vscale x 1 x i64> @intrinsic_vlseg6eff_mask_v_nxv1i64_nxv1i64(<vscale x 1 x i64>* %0, <vscale x 1 x i64> %1, <vscale x 1 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg6eff_mask_v_nxv1i64_nxv1i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg6eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg6eff_mask_v_nxv1i64_nxv1i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg6eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg6eff.mask.nxv1i64.nxv1i64(
    <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1,
    <vscale x 1 x i64>* %0,
    <vscale x 1 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 6
  store iXLen %c, iXLen* %4
  ret <vscale x 1 x i64> %b
}

declare { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg7eff.nxv1i64.nxv1i64(
  <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>,
  <vscale x 1 x i64>*,
  iXLen);

define <vscale x 1 x i64> @intrinsic_vlseg7eff_v_nxv1i64_nxv1i64(<vscale x 1 x i64>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg7eff_v_nxv1i64_nxv1i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg7eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg7eff_v_nxv1i64_nxv1i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg7eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg7eff.nxv1i64.nxv1i64(
    <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef,
    <vscale x 1 x i64>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 7
  store iXLen %c, iXLen* %2
  ret <vscale x 1 x i64> %b
}

declare { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg7eff.mask.nxv1i64.nxv1i64(
  <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>,
  <vscale x 1 x i64>*,
  <vscale x 1 x i1>,
  iXLen);

define <vscale x 1 x i64> @intrinsic_vlseg7eff_mask_v_nxv1i64_nxv1i64(<vscale x 1 x i64>* %0, <vscale x 1 x i64> %1, <vscale x 1 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg7eff_mask_v_nxv1i64_nxv1i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg7eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg7eff_mask_v_nxv1i64_nxv1i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg7eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg7eff.mask.nxv1i64.nxv1i64(
    <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1,
    <vscale x 1 x i64>* %0,
    <vscale x 1 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 7
  store iXLen %c, iXLen* %4
  ret <vscale x 1 x i64> %b
}

declare { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg8eff.nxv1i64.nxv1i64(
  <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>,
  <vscale x 1 x i64>*,
  iXLen);

define <vscale x 1 x i64> @intrinsic_vlseg8eff_v_nxv1i64_nxv1i64(<vscale x 1 x i64>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg8eff_v_nxv1i64_nxv1i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg8eff.v v7, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg8eff_v_nxv1i64_nxv1i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg8eff.v v7, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg8eff.nxv1i64.nxv1i64(
    <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef, <vscale x 1 x i64> undef,
    <vscale x 1 x i64>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 8
  store iXLen %c, iXLen* %2
  ret <vscale x 1 x i64> %b
}

declare { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg8eff.mask.nxv1i64.nxv1i64(
  <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>,
  <vscale x 1 x i64>*,
  <vscale x 1 x i1>,
  iXLen);

define <vscale x 1 x i64> @intrinsic_vlseg8eff_mask_v_nxv1i64_nxv1i64(<vscale x 1 x i64>* %0, <vscale x 1 x i64> %1, <vscale x 1 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg8eff_mask_v_nxv1i64_nxv1i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v7, v8
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v8
; RV32-NEXT:    th.vmv.v.v v14, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg8eff.v v7, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg8eff_mask_v_nxv1i64_nxv1i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v7, v8
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v8
; RV64-NEXT:    th.vmv.v.v v14, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg8eff.v v7, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } @llvm.riscv.th.vlseg8eff.mask.nxv1i64.nxv1i64(
    <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1, <vscale x 1 x i64> %1,
    <vscale x 1 x i64>* %0,
    <vscale x 1 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, <vscale x 1 x i64>, iXLen } %a, 8
  store iXLen %c, iXLen* %4
  ret <vscale x 1 x i64> %b
}

declare { <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } @llvm.riscv.th.vlseg2eff.nxv2i64.nxv2i64(
  <vscale x 2 x i64>, <vscale x 2 x i64>,
  <vscale x 2 x i64>*,
  iXLen);

define <vscale x 2 x i64> @intrinsic_vlseg2eff_v_nxv2i64_nxv2i64(<vscale x 2 x i64>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv2i64_nxv2i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV32-NEXT:    th.vlseg2eff.v v6, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv2i64_nxv2i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV64-NEXT:    th.vlseg2eff.v v6, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } @llvm.riscv.th.vlseg2eff.nxv2i64.nxv2i64(
    <vscale x 2 x i64> undef, <vscale x 2 x i64> undef,
    <vscale x 2 x i64>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 2 x i64> %b
}

declare { <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv2i64.nxv2i64(
  <vscale x 2 x i64>, <vscale x 2 x i64>,
  <vscale x 2 x i64>*,
  <vscale x 2 x i1>,
  iXLen);

define <vscale x 2 x i64> @intrinsic_vlseg2eff_mask_v_nxv2i64_nxv2i64(<vscale x 2 x i64>* %0, <vscale x 2 x i64> %1, <vscale x 2 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv2i64_nxv2i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v6, v8
; RV32-NEXT:    th.vmv.v.v v7, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV32-NEXT:    th.vlseg2eff.v v6, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv2i64_nxv2i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v6, v8
; RV64-NEXT:    th.vmv.v.v v7, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV64-NEXT:    th.vlseg2eff.v v6, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv2i64.nxv2i64(
    <vscale x 2 x i64> %1, <vscale x 2 x i64> %1,
    <vscale x 2 x i64>* %0,
    <vscale x 2 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 2 x i64> %b
}

declare { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } @llvm.riscv.th.vlseg3eff.nxv2i64.nxv2i64(
  <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>,
  <vscale x 2 x i64>*,
  iXLen);

define <vscale x 2 x i64> @intrinsic_vlseg3eff_v_nxv2i64_nxv2i64(<vscale x 2 x i64>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_v_nxv2i64_nxv2i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV32-NEXT:    th.vlseg3eff.v v6, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_v_nxv2i64_nxv2i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV64-NEXT:    th.vlseg3eff.v v6, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } @llvm.riscv.th.vlseg3eff.nxv2i64.nxv2i64(
    <vscale x 2 x i64> undef, <vscale x 2 x i64> undef, <vscale x 2 x i64> undef,
    <vscale x 2 x i64>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } %a, 3
  store iXLen %c, iXLen* %2
  ret <vscale x 2 x i64> %b
}

declare { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv2i64.nxv2i64(
  <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>,
  <vscale x 2 x i64>*,
  <vscale x 2 x i1>,
  iXLen);

define <vscale x 2 x i64> @intrinsic_vlseg3eff_mask_v_nxv2i64_nxv2i64(<vscale x 2 x i64>* %0, <vscale x 2 x i64> %1, <vscale x 2 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_mask_v_nxv2i64_nxv2i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v6, v8
; RV32-NEXT:    th.vmv.v.v v7, v9
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV32-NEXT:    th.vlseg3eff.v v6, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_mask_v_nxv2i64_nxv2i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v6, v8
; RV64-NEXT:    th.vmv.v.v v7, v9
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV64-NEXT:    th.vlseg3eff.v v6, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv2i64.nxv2i64(
    <vscale x 2 x i64> %1, <vscale x 2 x i64> %1, <vscale x 2 x i64> %1,
    <vscale x 2 x i64>* %0,
    <vscale x 2 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } %a, 3
  store iXLen %c, iXLen* %4
  ret <vscale x 2 x i64> %b
}

declare { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } @llvm.riscv.th.vlseg4eff.nxv2i64.nxv2i64(
  <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>,
  <vscale x 2 x i64>*,
  iXLen);

define <vscale x 2 x i64> @intrinsic_vlseg4eff_v_nxv2i64_nxv2i64(<vscale x 2 x i64>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_v_nxv2i64_nxv2i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV32-NEXT:    th.vlseg4eff.v v6, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_v_nxv2i64_nxv2i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV64-NEXT:    th.vlseg4eff.v v6, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } @llvm.riscv.th.vlseg4eff.nxv2i64.nxv2i64(
    <vscale x 2 x i64> undef, <vscale x 2 x i64> undef, <vscale x 2 x i64> undef, <vscale x 2 x i64> undef,
    <vscale x 2 x i64>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } %a, 4
  store iXLen %c, iXLen* %2
  ret <vscale x 2 x i64> %b
}

declare { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv2i64.nxv2i64(
  <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>,
  <vscale x 2 x i64>*,
  <vscale x 2 x i1>,
  iXLen);

define <vscale x 2 x i64> @intrinsic_vlseg4eff_mask_v_nxv2i64_nxv2i64(<vscale x 2 x i64>* %0, <vscale x 2 x i64> %1, <vscale x 2 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_mask_v_nxv2i64_nxv2i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v6, v8
; RV32-NEXT:    th.vmv.v.v v7, v9
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v9
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV32-NEXT:    th.vlseg4eff.v v6, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_mask_v_nxv2i64_nxv2i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v6, v8
; RV64-NEXT:    th.vmv.v.v v7, v9
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v9
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV64-NEXT:    th.vlseg4eff.v v6, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv2i64.nxv2i64(
    <vscale x 2 x i64> %1, <vscale x 2 x i64> %1, <vscale x 2 x i64> %1, <vscale x 2 x i64> %1,
    <vscale x 2 x i64>* %0,
    <vscale x 2 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, <vscale x 2 x i64>, iXLen } %a, 4
  store iXLen %c, iXLen* %4
  ret <vscale x 2 x i64> %b
}

declare { <vscale x 4 x i64>, <vscale x 4 x i64>, iXLen } @llvm.riscv.th.vlseg2eff.nxv4i64.nxv4i64(
  <vscale x 4 x i64>, <vscale x 4 x i64>,
  <vscale x 4 x i64>*,
  iXLen);

define <vscale x 4 x i64> @intrinsic_vlseg2eff_v_nxv4i64_nxv4i64(<vscale x 4 x i64>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv4i64_nxv4i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m4, d1
; RV32-NEXT:    th.vlseg2eff.v v4, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv4i64_nxv4i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m4, d1
; RV64-NEXT:    th.vlseg2eff.v v4, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i64>, <vscale x 4 x i64>, iXLen } @llvm.riscv.th.vlseg2eff.nxv4i64.nxv4i64(
    <vscale x 4 x i64> undef, <vscale x 4 x i64> undef,
    <vscale x 4 x i64>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x i64>, <vscale x 4 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i64>, <vscale x 4 x i64>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x i64> %b
}

declare { <vscale x 4 x i64>, <vscale x 4 x i64>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv4i64.nxv4i64(
  <vscale x 4 x i64>, <vscale x 4 x i64>,
  <vscale x 4 x i64>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x i64> @intrinsic_vlseg2eff_mask_v_nxv4i64_nxv4i64(<vscale x 4 x i64>* %0, <vscale x 4 x i64> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv4i64_nxv4i64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v4, v8
; RV32-NEXT:    th.vmv.v.v v5, v9
; RV32-NEXT:    th.vmv.v.v v6, v10
; RV32-NEXT:    th.vmv.v.v v7, v11
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m4, d1
; RV32-NEXT:    th.vlseg2eff.v v4, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv4i64_nxv4i64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v4, v8
; RV64-NEXT:    th.vmv.v.v v5, v9
; RV64-NEXT:    th.vmv.v.v v6, v10
; RV64-NEXT:    th.vmv.v.v v7, v11
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m4, d1
; RV64-NEXT:    th.vlseg2eff.v v4, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x i64>, <vscale x 4 x i64>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv4i64.nxv4i64(
    <vscale x 4 x i64> %1, <vscale x 4 x i64> %1,
    <vscale x 4 x i64>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x i64>, <vscale x 4 x i64>, iXLen } %a, 1
  %c = extractvalue { <vscale x 4 x i64>, <vscale x 4 x i64>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x i64> %b
}

declare { <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg2eff.nxv1f64.nxv1f64(
  <vscale x 1 x double>, <vscale x 1 x double>,
  <vscale x 1 x double>*,
  iXLen);

define <vscale x 1 x double> @intrinsic_vlseg2eff_v_nxv1f64_nxv1f64(<vscale x 1 x double>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv1f64_nxv1f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg2eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv1f64_nxv1f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg2eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg2eff.nxv1f64.nxv1f64(
    <vscale x 1 x double> undef, <vscale x 1 x double> undef,
    <vscale x 1 x double>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 1 x double> %b
}

declare { <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv1f64.nxv1f64(
  <vscale x 1 x double>, <vscale x 1 x double>,
  <vscale x 1 x double>*,
  <vscale x 1 x i1>,
  iXLen);

define <vscale x 1 x double> @intrinsic_vlseg2eff_mask_v_nxv1f64_nxv1f64( <vscale x 1 x double>* %0, <vscale x 1 x double> %1, <vscale x 1 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv1f64_nxv1f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg2eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv1f64_nxv1f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg2eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv1f64.nxv1f64(
    <vscale x 1 x double> %1, <vscale x 1 x double> %1,
    <vscale x 1 x double>* %0,
    <vscale x 1 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 1 x double> %b
}

declare { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg3eff.nxv1f64.nxv1f64(
  <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>,
  <vscale x 1 x double>*,
  iXLen);

define <vscale x 1 x double> @intrinsic_vlseg3eff_v_nxv1f64_nxv1f64(<vscale x 1 x double>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_v_nxv1f64_nxv1f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg3eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_v_nxv1f64_nxv1f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg3eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg3eff.nxv1f64.nxv1f64(
    <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef,
    <vscale x 1 x double>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 3
  store iXLen %c, iXLen* %2
  ret <vscale x 1 x double> %b
}

declare { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv1f64.nxv1f64(
  <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>,
  <vscale x 1 x double>*,
  <vscale x 1 x i1>,
  iXLen);

define <vscale x 1 x double> @intrinsic_vlseg3eff_mask_v_nxv1f64_nxv1f64( <vscale x 1 x double>* %0, <vscale x 1 x double> %1, <vscale x 1 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_mask_v_nxv1f64_nxv1f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg3eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_mask_v_nxv1f64_nxv1f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg3eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv1f64.nxv1f64(
    <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1,
    <vscale x 1 x double>* %0,
    <vscale x 1 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 3
  store iXLen %c, iXLen* %4
  ret <vscale x 1 x double> %b
}

declare { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg4eff.nxv1f64.nxv1f64(
  <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>,
  <vscale x 1 x double>*,
  iXLen);

define <vscale x 1 x double> @intrinsic_vlseg4eff_v_nxv1f64_nxv1f64(<vscale x 1 x double>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_v_nxv1f64_nxv1f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg4eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_v_nxv1f64_nxv1f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg4eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg4eff.nxv1f64.nxv1f64(
    <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef,
    <vscale x 1 x double>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 4
  store iXLen %c, iXLen* %2
  ret <vscale x 1 x double> %b
}

declare { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv1f64.nxv1f64(
  <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>,
  <vscale x 1 x double>*,
  <vscale x 1 x i1>,
  iXLen);

define <vscale x 1 x double> @intrinsic_vlseg4eff_mask_v_nxv1f64_nxv1f64( <vscale x 1 x double>* %0, <vscale x 1 x double> %1, <vscale x 1 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_mask_v_nxv1f64_nxv1f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg4eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_mask_v_nxv1f64_nxv1f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg4eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv1f64.nxv1f64(
    <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1,
    <vscale x 1 x double>* %0,
    <vscale x 1 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 4
  store iXLen %c, iXLen* %4
  ret <vscale x 1 x double> %b
}

declare { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg5eff.nxv1f64.nxv1f64(
  <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>,
  <vscale x 1 x double>*,
  iXLen);

define <vscale x 1 x double> @intrinsic_vlseg5eff_v_nxv1f64_nxv1f64(<vscale x 1 x double>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg5eff_v_nxv1f64_nxv1f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg5eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg5eff_v_nxv1f64_nxv1f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg5eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg5eff.nxv1f64.nxv1f64(
    <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef,
    <vscale x 1 x double>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 5
  store iXLen %c, iXLen* %2
  ret <vscale x 1 x double> %b
}

declare { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg5eff.mask.nxv1f64.nxv1f64(
  <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>,
  <vscale x 1 x double>*,
  <vscale x 1 x i1>,
  iXLen);

define <vscale x 1 x double> @intrinsic_vlseg5eff_mask_v_nxv1f64_nxv1f64( <vscale x 1 x double>* %0, <vscale x 1 x double> %1, <vscale x 1 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg5eff_mask_v_nxv1f64_nxv1f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg5eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg5eff_mask_v_nxv1f64_nxv1f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg5eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg5eff.mask.nxv1f64.nxv1f64(
    <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1,
    <vscale x 1 x double>* %0,
    <vscale x 1 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 5
  store iXLen %c, iXLen* %4
  ret <vscale x 1 x double> %b
}

declare { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg6eff.nxv1f64.nxv1f64(
  <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>,
  <vscale x 1 x double>*,
  iXLen);

define <vscale x 1 x double> @intrinsic_vlseg6eff_v_nxv1f64_nxv1f64(<vscale x 1 x double>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg6eff_v_nxv1f64_nxv1f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg6eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg6eff_v_nxv1f64_nxv1f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg6eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg6eff.nxv1f64.nxv1f64(
    <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef,
    <vscale x 1 x double>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 6
  store iXLen %c, iXLen* %2
  ret <vscale x 1 x double> %b
}

declare { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg6eff.mask.nxv1f64.nxv1f64(
  <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>,
  <vscale x 1 x double>*,
  <vscale x 1 x i1>,
  iXLen);

define <vscale x 1 x double> @intrinsic_vlseg6eff_mask_v_nxv1f64_nxv1f64( <vscale x 1 x double>* %0, <vscale x 1 x double> %1, <vscale x 1 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg6eff_mask_v_nxv1f64_nxv1f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg6eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg6eff_mask_v_nxv1f64_nxv1f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg6eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg6eff.mask.nxv1f64.nxv1f64(
    <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1,
    <vscale x 1 x double>* %0,
    <vscale x 1 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 6
  store iXLen %c, iXLen* %4
  ret <vscale x 1 x double> %b
}

declare { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg7eff.nxv1f64.nxv1f64(
  <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>,
  <vscale x 1 x double>*,
  iXLen);

define <vscale x 1 x double> @intrinsic_vlseg7eff_v_nxv1f64_nxv1f64(<vscale x 1 x double>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg7eff_v_nxv1f64_nxv1f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg7eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg7eff_v_nxv1f64_nxv1f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg7eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg7eff.nxv1f64.nxv1f64(
    <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef,
    <vscale x 1 x double>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 7
  store iXLen %c, iXLen* %2
  ret <vscale x 1 x double> %b
}

declare { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg7eff.mask.nxv1f64.nxv1f64(
  <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>,
  <vscale x 1 x double>*,
  <vscale x 1 x i1>,
  iXLen);

define <vscale x 1 x double> @intrinsic_vlseg7eff_mask_v_nxv1f64_nxv1f64( <vscale x 1 x double>* %0, <vscale x 1 x double> %1, <vscale x 1 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg7eff_mask_v_nxv1f64_nxv1f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v8
; RV32-NEXT:    th.vmv.v.v v14, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg7eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg7eff_mask_v_nxv1f64_nxv1f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v8
; RV64-NEXT:    th.vmv.v.v v14, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg7eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg7eff.mask.nxv1f64.nxv1f64(
    <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1,
    <vscale x 1 x double>* %0,
    <vscale x 1 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 7
  store iXLen %c, iXLen* %4
  ret <vscale x 1 x double> %b
}

declare { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg8eff.nxv1f64.nxv1f64(
  <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>,
  <vscale x 1 x double>*,
  iXLen);

define <vscale x 1 x double> @intrinsic_vlseg8eff_v_nxv1f64_nxv1f64(<vscale x 1 x double>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg8eff_v_nxv1f64_nxv1f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg8eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg8eff_v_nxv1f64_nxv1f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg8eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg8eff.nxv1f64.nxv1f64(
    <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef, <vscale x 1 x double> undef,
    <vscale x 1 x double>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 8
  store iXLen %c, iXLen* %2
  ret <vscale x 1 x double> %b
}

declare { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg8eff.mask.nxv1f64.nxv1f64(
  <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>,
  <vscale x 1 x double>*,
  <vscale x 1 x i1>,
  iXLen);

define <vscale x 1 x double> @intrinsic_vlseg8eff_mask_v_nxv1f64_nxv1f64( <vscale x 1 x double>* %0, <vscale x 1 x double> %1, <vscale x 1 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg8eff_mask_v_nxv1f64_nxv1f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v9, v8
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v8
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v8
; RV32-NEXT:    th.vmv.v.v v14, v8
; RV32-NEXT:    th.vmv.v.v v15, v8
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV32-NEXT:    th.vlseg8eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg8eff_mask_v_nxv1f64_nxv1f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v9, v8
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v8
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v8
; RV64-NEXT:    th.vmv.v.v v14, v8
; RV64-NEXT:    th.vmv.v.v v15, v8
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m1, d1
; RV64-NEXT:    th.vlseg8eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } @llvm.riscv.th.vlseg8eff.mask.nxv1f64.nxv1f64(
    <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1, <vscale x 1 x double> %1,
    <vscale x 1 x double>* %0,
    <vscale x 1 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, <vscale x 1 x double>, iXLen } %a, 8
  store iXLen %c, iXLen* %4
  ret <vscale x 1 x double> %b
}

declare { <vscale x 2 x double>, <vscale x 2 x double>, iXLen } @llvm.riscv.th.vlseg2eff.nxv2f64.nxv2f64(
  <vscale x 2 x double>, <vscale x 2 x double>,
  <vscale x 2 x double>*,
  iXLen);

define <vscale x 2 x double> @intrinsic_vlseg2eff_v_nxv2f64_nxv2f64(<vscale x 2 x double>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv2f64_nxv2f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV32-NEXT:    th.vlseg2eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv2f64_nxv2f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV64-NEXT:    th.vlseg2eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x double>, <vscale x 2 x double>, iXLen } @llvm.riscv.th.vlseg2eff.nxv2f64.nxv2f64(
    <vscale x 2 x double> undef, <vscale x 2 x double> undef,
    <vscale x 2 x double>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 2 x double>, <vscale x 2 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 2 x double>, <vscale x 2 x double>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 2 x double> %b
}

declare { <vscale x 2 x double>, <vscale x 2 x double>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv2f64.nxv2f64(
  <vscale x 2 x double>, <vscale x 2 x double>,
  <vscale x 2 x double>*,
  <vscale x 2 x i1>,
  iXLen);

define <vscale x 2 x double> @intrinsic_vlseg2eff_mask_v_nxv2f64_nxv2f64( <vscale x 2 x double>* %0, <vscale x 2 x double> %1, <vscale x 2 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv2f64_nxv2f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV32-NEXT:    th.vlseg2eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv2f64_nxv2f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV64-NEXT:    th.vlseg2eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x double>, <vscale x 2 x double>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv2f64.nxv2f64(
    <vscale x 2 x double> %1, <vscale x 2 x double> %1,
    <vscale x 2 x double>* %0,
    <vscale x 2 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 2 x double>, <vscale x 2 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 2 x double>, <vscale x 2 x double>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 2 x double> %b
}

declare { <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, iXLen } @llvm.riscv.th.vlseg3eff.nxv2f64.nxv2f64(
  <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>,
  <vscale x 2 x double>*,
  iXLen);

define <vscale x 2 x double> @intrinsic_vlseg3eff_v_nxv2f64_nxv2f64(<vscale x 2 x double>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_v_nxv2f64_nxv2f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV32-NEXT:    th.vlseg3eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_v_nxv2f64_nxv2f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV64-NEXT:    th.vlseg3eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, iXLen } @llvm.riscv.th.vlseg3eff.nxv2f64.nxv2f64(
    <vscale x 2 x double> undef, <vscale x 2 x double> undef, <vscale x 2 x double> undef,
    <vscale x 2 x double>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, iXLen } %a, 3
  store iXLen %c, iXLen* %2
  ret <vscale x 2 x double> %b
}

declare { <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv2f64.nxv2f64(
  <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>,
  <vscale x 2 x double>*,
  <vscale x 2 x i1>,
  iXLen);

define <vscale x 2 x double> @intrinsic_vlseg3eff_mask_v_nxv2f64_nxv2f64( <vscale x 2 x double>* %0, <vscale x 2 x double> %1, <vscale x 2 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg3eff_mask_v_nxv2f64_nxv2f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v9
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV32-NEXT:    th.vlseg3eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg3eff_mask_v_nxv2f64_nxv2f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v9
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV64-NEXT:    th.vlseg3eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, iXLen } @llvm.riscv.th.vlseg3eff.mask.nxv2f64.nxv2f64(
    <vscale x 2 x double> %1, <vscale x 2 x double> %1, <vscale x 2 x double> %1,
    <vscale x 2 x double>* %0,
    <vscale x 2 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, iXLen } %a, 3
  store iXLen %c, iXLen* %4
  ret <vscale x 2 x double> %b
}

declare { <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, iXLen } @llvm.riscv.th.vlseg4eff.nxv2f64.nxv2f64(
  <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>,
  <vscale x 2 x double>*,
  iXLen);

define <vscale x 2 x double> @intrinsic_vlseg4eff_v_nxv2f64_nxv2f64(<vscale x 2 x double>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_v_nxv2f64_nxv2f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV32-NEXT:    th.vlseg4eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_v_nxv2f64_nxv2f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV64-NEXT:    th.vlseg4eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, iXLen } @llvm.riscv.th.vlseg4eff.nxv2f64.nxv2f64(
    <vscale x 2 x double> undef, <vscale x 2 x double> undef, <vscale x 2 x double> undef, <vscale x 2 x double> undef,
    <vscale x 2 x double>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, iXLen } %a, 4
  store iXLen %c, iXLen* %2
  ret <vscale x 2 x double> %b
}

declare { <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv2f64.nxv2f64(
  <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>,
  <vscale x 2 x double>*,
  <vscale x 2 x i1>,
  iXLen);

define <vscale x 2 x double> @intrinsic_vlseg4eff_mask_v_nxv2f64_nxv2f64( <vscale x 2 x double>* %0, <vscale x 2 x double> %1, <vscale x 2 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg4eff_mask_v_nxv2f64_nxv2f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v10, v8
; RV32-NEXT:    th.vmv.v.v v11, v9
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v9
; RV32-NEXT:    th.vmv.v.v v14, v8
; RV32-NEXT:    th.vmv.v.v v15, v9
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV32-NEXT:    th.vlseg4eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg4eff_mask_v_nxv2f64_nxv2f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v10, v8
; RV64-NEXT:    th.vmv.v.v v11, v9
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v9
; RV64-NEXT:    th.vmv.v.v v14, v8
; RV64-NEXT:    th.vmv.v.v v15, v9
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m2, d1
; RV64-NEXT:    th.vlseg4eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, iXLen } @llvm.riscv.th.vlseg4eff.mask.nxv2f64.nxv2f64(
    <vscale x 2 x double> %1, <vscale x 2 x double> %1, <vscale x 2 x double> %1, <vscale x 2 x double> %1,
    <vscale x 2 x double>* %0,
    <vscale x 2 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, <vscale x 2 x double>, iXLen } %a, 4
  store iXLen %c, iXLen* %4
  ret <vscale x 2 x double> %b
}

declare { <vscale x 4 x double>, <vscale x 4 x double>, iXLen } @llvm.riscv.th.vlseg2eff.nxv4f64.nxv4f64(
  <vscale x 4 x double>, <vscale x 4 x double>,
  <vscale x 4 x double>*,
  iXLen);

define <vscale x 4 x double> @intrinsic_vlseg2eff_v_nxv4f64_nxv4f64(<vscale x 4 x double>* %0, iXLen %1, iXLen* %2) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_v_nxv4f64_nxv4f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    th.vsetvli zero, a1, e64, m4, d1
; RV32-NEXT:    th.vlseg2eff.v v8, (a0)
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_v_nxv4f64_nxv4f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    th.vsetvli zero, a1, e64, m4, d1
; RV64-NEXT:    th.vlseg2eff.v v8, (a0)
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x double>, <vscale x 4 x double>, iXLen } @llvm.riscv.th.vlseg2eff.nxv4f64.nxv4f64(
    <vscale x 4 x double> undef, <vscale x 4 x double> undef,
    <vscale x 4 x double>* %0,
    iXLen %1)

  %b = extractvalue { <vscale x 4 x double>, <vscale x 4 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x double>, <vscale x 4 x double>, iXLen } %a, 2
  store iXLen %c, iXLen* %2
  ret <vscale x 4 x double> %b
}

declare { <vscale x 4 x double>, <vscale x 4 x double>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv4f64.nxv4f64(
  <vscale x 4 x double>, <vscale x 4 x double>,
  <vscale x 4 x double>*,
  <vscale x 4 x i1>,
  iXLen);

define <vscale x 4 x double> @intrinsic_vlseg2eff_mask_v_nxv4f64_nxv4f64( <vscale x 4 x double>* %0, <vscale x 4 x double> %1, <vscale x 4 x i1> %2, iXLen %3, iXLen* %4) nounwind {
; RV32-LABEL: intrinsic_vlseg2eff_mask_v_nxv4f64_nxv4f64:
; RV32:       # %bb.0: # %entry
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    csrr a3, vl
; RV32-NEXT:    csrr a4, vtype
; RV32-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV32-NEXT:    th.vmv.v.v v12, v8
; RV32-NEXT:    th.vmv.v.v v13, v9
; RV32-NEXT:    th.vmv.v.v v14, v10
; RV32-NEXT:    th.vmv.v.v v15, v11
; RV32-NEXT:    th.vsetvl zero, a3, a4
; RV32-NEXT:    th.vsetvli zero, a1, e64, m4, d1
; RV32-NEXT:    th.vlseg2eff.v v8, (a0), v0.t
; RV32-NEXT:    csrr a0, vl
; RV32-NEXT:    sw a0, 0(a2)
; RV32-NEXT:    ret
;
; RV64-LABEL: intrinsic_vlseg2eff_mask_v_nxv4f64_nxv4f64:
; RV64:       # %bb.0: # %entry
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    csrr a3, vl
; RV64-NEXT:    csrr a4, vtype
; RV64-NEXT:    th.vsetvli zero, zero, e8, m1, d1
; RV64-NEXT:    th.vmv.v.v v12, v8
; RV64-NEXT:    th.vmv.v.v v13, v9
; RV64-NEXT:    th.vmv.v.v v14, v10
; RV64-NEXT:    th.vmv.v.v v15, v11
; RV64-NEXT:    th.vsetvl zero, a3, a4
; RV64-NEXT:    th.vsetvli zero, a1, e64, m4, d1
; RV64-NEXT:    th.vlseg2eff.v v8, (a0), v0.t
; RV64-NEXT:    csrr a0, vl
; RV64-NEXT:    sd a0, 0(a2)
; RV64-NEXT:    ret
entry:
  %a = call { <vscale x 4 x double>, <vscale x 4 x double>, iXLen } @llvm.riscv.th.vlseg2eff.mask.nxv4f64.nxv4f64(
    <vscale x 4 x double> %1, <vscale x 4 x double> %1,
    <vscale x 4 x double>* %0,
    <vscale x 4 x i1> %2,
    iXLen %3)

  %b = extractvalue { <vscale x 4 x double>, <vscale x 4 x double>, iXLen } %a, 0
  %c = extractvalue { <vscale x 4 x double>, <vscale x 4 x double>, iXLen } %a, 2
  store iXLen %c, iXLen* %4
  ret <vscale x 4 x double> %b
}

;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
